Refactor tooltip
repaygithub/cactus pull request #311
Opened 2020-08-31 20:14 UTC by NicolasSimmonds

Testing:

- Make sure the default tooltip shows op on the top left, and check it adjusts well on collisions
- Take a look at the tooltip icon and make sure it matches the Styleguide

2020-09-01 17:31 UTC, Dhalton commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> +  const handleFieldFocus = () => {
Kind of nit-picky but can we rename this function to `toggleTooltip` or something to that effect? I only bring it up because this function is passed to both `onFocus` and `onBlur`, so the function name is slightly misleading.

2020-09-01 19:29 UTC, mikesoltow commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
>          ? props.children(accessibility)
I agree with Dhalton that all components that use the `AccessibleField` component should have this focus behavior.  You can accomplish this by passing down the focus/blur handlers into the `props.children` function.  You'd then have to actually wire those handlers up in the components that use the children-as-function form of `AccessibleField`.

2020-09-01 19:33 UTC, mikesoltow commented
@NicolasSimmonds I also forgot one other thing in my review.  I'd recommend using a prop on the `Tooltip` component, such as `forceVisible`, to control the visibility as opposed to making `AccessibleField` interact with a ref.  The prop could be toggled in the focus/blur handlers.  I think this would be a bit easier to follow and requires less knowledge from components that consume `Tooltip`.  See https://github.com/repaygithub/cactus/commit/726e32182136cc2fdba66e658c2eeaa86e695379 for an example.

2020-09-02 19:17 UTC, Dhalton reviewed
Looks good to me, there are just a couple of small things in the `SelectField` tests but other than that I'm ready to approve

2020-09-02 19:17 UTC, Dhalton commented on modules/cactus-web/src/SelectField/SelectField.test.tsx
> +      expect(onBlur).toHaveBeenCalled
This should be a function call

2020-09-02 19:17 UTC, Dhalton commented on modules/cactus-web/src/SelectField/SelectField.test.tsx
> +      console.log(onFocus())
Probably don't need this console log here

2020-09-02 20:46 UTC, Dhalton approved these changes
LGTM, thanks for making those changes!

2020-09-03 17:25 UTC, mikesoltow reviewed
Changes look great!  Just one question regarding the `DateInputField`, then I'm good with this.

2020-09-03 17:25 UTC, mikesoltow commented on modules/cactus-web/src/DateInputField/DateInputField.tsx
> +          onBlur={handleFieldBlur}
Why don't you also handle `onFocus`/`onBlur` events passed into `DateInputField` (like you do with the other components)?

2020-09-03 18:43 UTC, NicolasSimmonds commented on modules/cactus-web/src/DateInputField/DateInputField.tsx
> +          onBlur={handleFieldBlur}
Ups, I guess I missed that

2020-09-03 21:56 UTC, wilysword requested changes
I like the changes to the tooltip, but I think the changes to `AccessibleField` are a little too invasive. Should be easy enough to fix, though.

2020-09-03 21:56 UTC, wilysword commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> +            onBlur: handleFieldBlur,
Setting these will override any handlers the dev has already assigned to the child element, leaving their only option to use a render func and then frankenstein the two handlers together. I would suggest putting the `RenderFunc` type back how it was, removing these from the cloneElement call, and instead setting them on the `FieldWrapper`. The focus/blur events will bubble up from the child element so you can still set/unset the tooltip visibility, but without compromising the dev's control over the child.

```
<FieldWrapper className={props.className} ref={ref} onFocus={handleFieldFocus} onBlur={handleFieldBlur}>
```

2020-09-03 21:56 UTC, wilysword commented on modules/cactus-web/src/Tooltip/Tooltip.tsx
> +  border-color: ${(p): string => p.theme.colors.callToAction};
This is redundant with the `border` declaration on line 139.

2020-09-04 16:36 UTC, wilysword approved these changes

2020-09-04 18:42 UTC, mikesoltow reviewed
Changes look good!  Just a couple of questions about the remaining event handlers.

2020-09-08 17:34 UTC, mikesoltow reviewed
Thanks for the changes!  Unfortunately I found one more thing right before I was going to approve 😢

2020-09-08 17:34 UTC, mikesoltow commented on modules/cactus-web/src/Tooltip/Tooltip.tsx
>  const StyledInfo = styled(NotificationInfo)<StyledInfoProps>`
One more thing.  I'm seeing console errors related to the fact that the `forceVisible` prop is being passed all the way down to the icon SVG, and React isn't recognizing it as a valid HTML prop.  We'll need to filter it out to get rid of that error.

```suggestion
styled(({ forceVisible, ...props }) => <NotificationInfo {...props} />)<
  StyledInfoProps
>`
```

2020-09-08 17:37 UTC, wilysword commented on modules/cactus-web/src/Tooltip/Tooltip.tsx
>  const StyledInfo = styled(NotificationInfo)<StyledInfoProps>`
Alternative ways of doing the same thing: https://styled-components.com/docs/api#transient-props

2020-09-08 17:56 UTC, NicolasSimmonds commented on modules/cactus-web/src/Tooltip/Tooltip.tsx
>  const StyledInfo = styled(NotificationInfo)<StyledInfoProps>`
I liked Glen's idea. Updated

2020-09-08 18:05 UTC, mikesoltow commented on modules/cactus-web/src/Tooltip/Tooltip.tsx
>  const StyledInfo = styled(NotificationInfo)<StyledInfoProps>`
One downside to transient props, however, is that it's only available in Styled Components v5.  That would require a breaking Cactus change, as currently we support apps that use Styled Components v4.  Therefore my vote is to do it the non-transient way, as I don't think this refactor is worth a breaking change.

2020-09-08 18:48 UTC, mikesoltow approved these changes
Thanks for the changes!  Looks good to me!

2020-09-08 18:49 UTC, merged