CACTUS-333 ActionBar Component
repaygithub/cactus pull request #343
Opened 2020-09-23 16:14 UTC by wilysword

https://repayonline.atlassian.net/browse/CACTUS-333

There are two outstanding issues (that I know of):
1. In the Layout story, sometimes when un-checking the MenuBar knob you get a console warning about setting state of an unmounted component. I don't think that's because of the ActionBar, but I couldn't pinpoint the cause so I'm not positive.
2. The ActionBar doesn't style correctly when it's not inside Layout. I'd like to fix this in a followup ticket where we decouple the `Sidebar` from `Layout`, because it's more refactoring than I felt comfortable with in this ticket.

2020-09-23 18:37 UTC, Dhalton approved these changes

2020-09-25 14:51 UTC, NicolasSimmonds reviewed
Are you planning to include the Live code example once the ActionBar.Panel is finished? Or why didn't you include it?

2020-09-25 16:18 UTC, wilysword commented
I might add one later, but the components with fixed positioning are rather annoying in the live demo (e.g. try looking at Footer).

2020-09-25 16:27 UTC, NicolasSimmonds approved these changes

2020-09-25 17:15 UTC, mikesoltow requested changes
I'm just skimming this out of curiosity (cause it's awesome), not actually reviewing it.  But I did notice one typo in the docs.  Then I'm happy to merge!

2020-09-25 17:15 UTC, mikesoltow commented on modules/cactus-web/src/ActionBar/ActionBar.mdx
> +    <ActionBar.Content>
I assume you mean Layout.Content here?

2020-09-25 17:16 UTC, wilysword commented on modules/cactus-web/src/ActionBar/ActionBar.mdx
> +    <ActionBar.Content>
Find & replace strikes again.

2020-09-28 16:27 UTC, mikesoltow approved these changes

2020-09-28 18:50 UTC, merged