fix(cactus-web): ignore width on card view of table and Datagrid
repaygithub/cactus pull request #347
Opened 2020-09-29 16:56 UTC by NicolasSimmonds

Check that the width prop is ignored in card view in both DataGrid and Table

[CACTUS-374]

2020-09-29 20:47 UTC, Dhalton approved these changes
LGTM 👍

2020-09-30 20:43 UTC, mikesoltow commented on modules/cactus-web/src/Table/Table.tsx
> +        width: 288px;
What would you think about bumping this down to `272`?  I notice that it overflows the screen on iPhone 5.  It overflows at 272 as well, but not by as much, at least.

2020-09-30 20:52 UTC, mikesoltow requested changes
Ooops, I actually found an IE11 bug.

<img width="1287" alt="Screen Shot 2020-09-30 at 4 45 28 PM" src="https://user-images.githubusercontent.com/46460514/94738204-111e0300-033d-11eb-920d-8789cd5d94d0.png">

I think you can get rid of this by removing the `max-width: 100%` in the `HeaderBox` and `ContentBox` (for card mode only!), although I'm not sure if that will have any adverse effects.

2020-09-30 21:03 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +        width: 288px;
Yaeah its fine by me!

2020-10-01 17:29 UTC, Dhalton commented
I'm still seeing the text overflowing on the cards in IE11

2020-10-01 17:33 UTC, NicolasSimmonds commented
> I'm still seeing the text overflowing on the cards in IE11

Really? Thats weird. I don't see the text overflowing at all

2020-10-01 19:20 UTC, mikesoltow commented
@NicolasSimmonds I can reproduce it in IE11 if I reduce the width of the browser window to tiny/small size.  For some reason, changing the width to `240px` fixes it.  And I'd recommend that anyway because that makes the width of the entire card, including padding, equal to 272, which is what the Style Guide intended from what I can see.

2020-10-01 23:02 UTC, Dhalton approved these changes
Re-approving for the latest changes. Looks good in IE 👍

2020-10-02 14:18 UTC, mikesoltow approved these changes
Agreed...latest changes look good!

2020-10-05 18:18 UTC, merged