Splitbutton variants
repaygithub/cactus pull request #349
Opened 2020-10-01 14:24 UTC by NicolasSimmonds

In  storybook, go to the basic usage split button, and test that the three variants match the Styleguide.

[CACTUS-354]

2020-10-02 14:36 UTC, mikesoltow requested changes
Just a few comments

2020-10-02 14:36 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +            border-color: ${(p): string => p.theme.colors.error};
```suggestion
            border-color: ${(p): string => p.theme.colors.errorDark};
```

2020-10-02 14:36 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +            border-color: ${(p): string => p.theme.colors.success};
```suggestion
            border-color: ${(p): string => p.theme.colors.successDark};
```

2020-10-02 14:36 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +  variant: 'standard',
We should probably add this to `propTypes` too

2020-10-02 14:36 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +    }
Why did you move these styles out of the `DropdownButton` styled component?  By putting them here, you're putting them in conflict with the styles defined up there...mostly notably the `disabled` styles.  As a result, the dropdown button now has a color even when the split button is disabled.

2020-10-02 14:42 UTC, NicolasSimmonds commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +    }
I did this so that I didn't have to create an interface for the dropdown button and the Menubutton and pass the variant into those components. But I guess it was a bad call. Will change this

2020-10-02 14:44 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +    }
Ah gotcha.  If you still want to avoid that, you could...you'd just have to make a clear separation of which style attributes go in which group of styles (i.e. `background-color` should be controlled here).

It's probably more readable to change it, but I'm just saying you don'g _have_ to 😄

2020-10-05 18:35 UTC, mikesoltow approved these changes
Changes look good!

2020-10-05 18:35 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.tsx
> +  VARIANT: PropTypes.oneOf(['standard', 'danger', 'success']),
Don't think this matters too much, but we might as well change this to lower-case before we merge.

2020-10-05 22:41 UTC, wilysword approved these changes

2020-10-06 17:29 UTC, merged