CACTUS-375 :: Configurable Card Padding
repaygithub/cactus pull request #353
Opened 2020-10-07 22:40 UTC by Dhalton

Ticket: https://repayonline.atlassian.net/browse/CACTUS-375

Testing should be pretty simple; just bring up the storybook and use the new knobs to make sure all of the acceptance criteria are being met.

2020-10-08 16:22 UTC, mikesoltow approved these changes
This all looks great so I'm going to approve

...with a question (that you'll hate me for only thinking of now 🤦 ):

Should we just abandon the small/medium/large levels and use the standard styled-system levels for consistency?  We could still default `padding` to `4` and tell the users in the docs that we recommend using 4, 5, or 7 (minimum of 5 when nesting).  But that way they have flexibility and can use the same system that we use with other components?

2020-10-08 17:05 UTC, Dhalton commented
> Should we just abandon the small/medium/large levels and use the standard styled-system levels for consistency? We could still default `padding` to `4` and tell the users in the docs that we recommend using 4, 5, or 7 (minimum of 5 when nesting). But that way they have flexibility and can use the same system that we use with other components?

Yeah that's probably a good idea. I'll do this today. I think that's actually easier to implement, anyway.

2020-10-08 22:31 UTC, wilysword approved these changes

2020-10-09 15:44 UTC, mikesoltow requested changes
Just one requested change that was really just an oversight with the ACs.  Feel free to push back if you disagree, however.

2020-10-09 15:44 UTC, mikesoltow commented on modules/cactus-web/src/Card/Card.tsx
>    & > & {
I know this wasn't in the ACs, but I think that's just because I forgot these were there: I think we should probably delete these hard-coded nested styles and make them configurable by the developer.  Otherwise, these styles will overwrite anything the developer passes in for padding, which is not the intent.

2020-10-09 18:24 UTC, Dhalton commented on modules/cactus-web/src/Card/Card.tsx
>    & > & {
Oh, yeah I'm pretty sure I had gotten rid of those the first time but must've forgot to get rid of them again after I reset the commits 🤦 I'll remove them. Thanks for letting me know!

2020-10-09 19:20 UTC, mikesoltow approved these changes
Re-approved!

2020-10-09 20:50 UTC, merged