fix(cactus-web): fix height of table with long values
repaygithub/cactus pull request #355
Opened 2020-10-08 17:02 UTC by NicolasSimmonds

There is a knew story for the Table in the storybook in which you can see the result. 
If you want to see a different length, or behavior for other cell, the text should be changed in the code because of the way this is calculated; it does not work as a knob.

[CACTUS-370]

2020-10-08 18:44 UTC, Dhalton reviewed
Looks good for the most part, but I did notice some weirdness as I was testing. If you open the new story you added for the long values, and then go back to the basic usage story and change the screen size so that it renders in card view, you'll see the "row" has the same height as it did for the other story, even though there's no need for it.

It looks like the context still has the same value for `largestCell`, causing it to be rendered in the same way. I wonder if cleaning out that context when the component unmounts would fix the issue. That's what I'd try.

2020-10-08 20:14 UTC, NicolasSimmonds commented
> Looks good for the most part, but I did notice some weirdness as I was testing. If you open the new story you added for the long values, and then go back to the basic usage story and change the screen size so that it renders in card view, you'll see the "row" has the same height as it did for the other story, even though there's no need for it.
> 
> It looks like the context still has the same value for `largestCell`, causing it to be rendered in the same way. I wonder if cleaning out that context when the component unmounts would fix the issue. That's what I'd try.

Yeah I did tried this for other issue but form some reason the styles wont't apply to the first row. I can try and find another solution to it though

2020-10-09 16:15 UTC, wilysword commented
Shouldn't you commit the changes first so we can review the most up-to-date version, rather than having to review it twice?

2020-10-09 18:30 UTC, wilysword requested changes
The algorithm seems like a good start, but it's still pretty flawed:

- It's using what is effectively a global variable
- It appears to only work for a single column at a time

I also have a couple of suggestions to make your algorithm more flexible:
- Instead of `style.height`, set `style.minHeight`
- On the tallest cell(s), set `style.minHeight = ''`; that way if the value in that cell shrinks, you can recalculate the min height for all the other cells in the column

2020-10-09 18:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +        }
I'd move this to the `ContentBox` styles as
```
${HeaderBox}:not(:empty) + & {
  align-self: flex-end;
}
```

2020-10-09 18:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
>  }
I think the problem Dhalton mentioned is because when you make a copy of the context it's a shallow copy, meaning this `largestCell` property is actually a global value, the way you're using it.

2020-10-09 18:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +        combinedRef.current.style.height = `${context.largestCell.height - 16}px`
Assuming this -16 is a padding issue, we should probably make the cells `box-sizing: border-box;`.

2020-10-09 18:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +    cell: 0,
I think this wouldn't work if you had multiple cells with large values; you'd need to get the largest cell _per column_.

2020-10-09 18:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +            context.largestCell.cell = combinedRef.current.cellIndex
Should probably account for `colSpan`, like the calculations on `context.cellIndex`.

2020-10-09 19:19 UTC, mikesoltow commented on modules/cactus-web/src/Table/Table.tsx
> +      }, [combinedRef, context.largestCell.cell, context.largestCell.height, ref, children])
I'm bummed that the linter didn't catch this 😢   After fiddling, the linter only catches it in regular components, not in a forwardRef callback.  It's weird, though, cause they had an issue that fixed this a while back.  I wonder if using TypeScript messes with their fix somehow.  https://github.com/facebook/react/issues/17220

2020-10-13 19:45 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +            context.largestCell.cell = combinedRef.current.cellIndex
I don't think I understand what you meant here

2020-10-13 19:52 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +            context.largestCell.cell = combinedRef.current.cellIndex
Look up at lines 143-147. `colSpan` is an attribute that makes a cell take up more than one column, and it's not the same for every cell in a column. If you have a cell at index 1 with `colSpan=2`, then the cell index of the next cell in the row is 3, not 2, because cell 1 takes up two columns. Not sure I'm very good at explaining that, so let me know if I'm still not being clear.

2020-10-13 21:43 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +            context.largestCell.cell = combinedRef.current.cellIndex
So to see if I understood correctly, I should take the colSpan value into account when it's 2 or more and make the cell at index x and subsequent cells untill colSpan value, the same height?

2020-10-13 21:59 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
>  }
The problem is that if I don't make this a global variable, the value of the largest cell(s) is lost after each TableCell is rendered. So I have no way to persist those values. Any Ideas on this?

2020-10-13 22:30 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +            context.largestCell.cell = combinedRef.current.cellIndex
Hmm, I hadn't thought about the actual algorithm, and now that I am I'm coming up blank. We may want to come back to this eventually, but I think for now it might be best to just ignore `colSpan` after all. Your understanding of the issue seems correct, though.

2020-10-14 14:41 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +}
Ive been trying to use the function ate helpers/react.ts, but I don't think I fully understand it. When I use it and save the combined refs in a variable, the variable is a function, not an actual ref so I can't access the current property or anything

2020-10-14 14:57 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
>  }
The problem Dhalton mentioned is already resolved. But I'm not sure how to modify the context in a non-global way. The way cellIndex and headers is being modified is the same as largestCell, as far as I can tell.

2020-10-14 17:41 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +}
You've got the code
```
const innerRef = React.useRef(null)
const combinedRef = useCombinedRefs(ref, innerRef)
```
and then you use the `combinedRef` as if it were a normal ref, and just ignore `innerRef`. What you want is
```
const innerRef = React.useRef<HTMLTableDataCellElement>(null)
const combinedRef = useMergedRefs(ref, innerRef)
...
<StyledCell {...props} ref={combinedRef}>
```
so you still pass the combined ref to the element, but change all other references to `combinedRef` to use `innerRef` instead.

2020-10-14 17:49 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
>  }
It's not the same, because `largestCell` is a nested object. Consider the following:
```js
const x = { one: 'uno', two: { value: 'dos' } }
const y = { ...x }
y.one = 'ein'
y.two.value = 'zwei'

x.one === 'uno'
x.two.value === 'zwei'
```
`y` is a _shallow_ copy of `x`, so you can change values at the top level without affecting the original; but the nested object `two` is the same reference in both so changes to one affect the other. That's what's happening with the context. To stop doing that you either need to stop nesting those values, or do a _deep_ copy of the default context.

2020-10-15 21:10 UTC, Dhalton commented on modules/cactus-web/src/Table/Table.tsx
> +interface CellHeightProps {
I don't think you need this interface anymore. I don't see it being used anywhere

2020-10-16 18:31 UTC, wilysword reviewed
I couldn't get it to update properly like this, so after playing around for a bit I came up with https://github.com/repaygithub/cactus/commit/50b83f9d176b040134efc3c560dd3b4bb0d69848. It doesn't require any of the context changes, and it seems to work pretty well; it can grow if the cell contents grow, but it can't shrink if they shrink.

2020-10-16 19:01 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +    min-width: fit-content;
The reason for this is that when I changed the contentbox to box-sizing: border-box, the width was smaller than the actual cell. I guess I can change that

2020-10-20 17:43 UTC, wilysword reviewed
Code looks good, and everything seems to be working. Unfortunately, as usual IE can't allow us to have nice things:
![ie-table](https://user-images.githubusercontent.com/7714951/96621884-0e6c5900-12be-11eb-859a-d7d8304dcc1c.png)

Adding `box-sizing: border-box;` to `StyledCell` made it look better, so it's probably due to a discrepancy between the `tr` width and the cell width.

2020-10-20 21:01 UTC, Dhalton approved these changes
Nice, code looks good and it's working much better now. Thanks for sticking this out 👍

2020-10-21 16:56 UTC, wilysword approved these changes

2020-10-21 21:13 UTC, merged