CACTUS-342 Part 2: The Custom EventTarget Solution
repaygithub/cactus pull request #366
Opened 2020-10-23 19:29 UTC by wilysword

[CACTUS-342](https://repayonline.atlassian.net/browse/CACTUS-342)

Still have a couple more components to implement, but I wanted to get feedback on the solution I'm pursuing before I applied it to everything.

I strongly recommend you look at the diff while hiding whitespace changes; there's a sizable chunk of code that I purposefully left where it was (despite desperately wanting to reorganize it) specifically to make the diff smaller.

I would love to do DOM standard instead of React standard, but most of the best improvements in custom events aren't supported by IE 11, and even with the newer stuff it's hard to make custom event targets that bubble. So I'm stuck with non-bubbling React events.

2020-10-26 16:15 UTC, NicolasSimmonds reviewed
I like the way you are handling the events and don't see any problems whatsoever

2020-10-28 14:23 UTC, mikesoltow reviewed
Leaving a few comments I had on the FileInput stuff.  This morning I'll take another look at the delete file issue I mentioned yesterday to see if that's a real thing, then later today I'll take a look at the rest of the code.

Overall, good stuff!

2020-10-28 16:03 UTC, wilysword commented on modules/cactus-web/src/helpers/events.ts
> +  const focused = isIE ? document.activeElement : event.relatedTarget
I'd say separate ticket, since this should work fine in either version.

2020-10-28 16:06 UTC, wilysword commented on modules/cactus-web/src/FileInput/FileInput.tsx
> +  const box = useBox<PropBox>({
Yes, that's exactly it; it's basically like doing `this.suchAndSuch` on a class component. It's less useful for effects (since you usually _want_ those to re-run when values change), but it allows you to write completely stable callbacks which nevertheless have the latest values.

2020-10-28 16:16 UTC, wilysword commented on modules/cactus-web/src/FileInput/FileInput.tsx
> +  const reducer = useRef<React.Reducer<FileObject[], FileAction>>()
tl;dr: Apparently the reducer needs to have a stable value. I could have done `useCallback` but I don't trust that quite as much since the docs say it behaves like `useMemo`, which suggests but doesn't _guarantee_ stability.

This one actually threw me off too; I originally had it as a simple function, assuming that `useReducer` would just use whatever was passed in first and ignore subsequent calls (as it does for the initial value argument). When I tested it, though, I immediately started getting weird errors and, a few `console.log`s later, I noticed that a single dispatch was running the reducer three times which also happened to be the number of times the component had rendered at that point. The specific pattern of setting the reducer's value in an if statement instead of passing it to `useRef` is something I saw in some 3rd party library code, presumably an optimization so the function doesn't have to be defined (and then garbage-collected without being used) every time the component renders.

2020-10-28 16:38 UTC, mikesoltow requested changes
I think I found the source of the delete bug I mentioned yesterday, but let me know if you think this is incorrect.

2020-10-28 16:38 UTC, mikesoltow commented on modules/cactus-web/src/FileInput/FileInput.tsx
> -    setState({ files: files, inputKey: Math.random().toString(36) })
I haven't proven it, but I think deleting this `inputKey` is what is causing the delete error.  The delete error only happens if you try to re-add the file you just deleted.  I think the reason is that `onChange` on the `input` is never triggered because the input thinks the selected file is already part of the value.  Changing the key on delete must "reset" the input, which is why it was working before.

That being said, I'm not sure if that's desirable behavior if you only delete one file out of several...but maybe that doesn't matter?  Maybe it just matters what our internal file state is, and we don't care about the value of the input (except when it causes bugs like this).

2020-10-28 17:15 UTC, mikesoltow commented on modules/cactus-web/src/FileInput/FileInput.tsx
> +  const reducer = useRef<React.Reducer<FileObject[], FileAction>>()
Interesting.  That's annoying, but it makes sense.  I suppose that the reason I've never seen this pattern before is that I've almost always seen reducers defined outside their components.  And come to think of it, that probably makes more sense anyway since they are supposed to be pure functions.  The way this is currently implemented, it's not really pure because it relies on `box`.

What would you think about moving the reducer definition outside the component and passing `box` in the action?

2020-10-28 17:22 UTC, wilysword commented on modules/cactus-web/src/FileInput/FileInput.tsx
> +  const reducer = useRef<React.Reducer<FileObject[], FileAction>>()
That's certainly possible, but to me it seems like adding code just for the sake of being pedantic. This isn't that different than doing `useState` and then defining a function to replace/abstract away `setValue` because it's always called the same way; we've done that in quite a few places. I just inverted the pattern and defined the function before the hook instead of after it. Still, if you feel strongly about it I can come up with something.

2020-10-28 17:29 UTC, mikesoltow commented on modules/cactus-web/src/FileInput/FileInput.tsx
> +  const reducer = useRef<React.Reducer<FileObject[], FileAction>>()
That's certainly fair, as I don't want to follow the rules _just_ to follow the rules.  However, I do have some concern here because React makes the assumption that all reducer functions are pure, so I worry that it could cause some unintended side effects at some point.

Speaking of side effects, I just realized that the reducer code also modifies `box`.  Is there any way we can move `event` to the reducer's state if we need to access it elsewhere?

Again, I'm more than open to being convinced that the way you have it is fine, I'm just hesitant to go against the library's assumptions for how we'll be using it without being 100% sure.

2020-10-29 20:09 UTC, wilysword commented
@mikesoltow Hopefully I've addressed your concerns with the latest commit, though the diff is much messier as a result.

2020-10-30 18:48 UTC, mikesoltow commented
@wilysword Thanks for the changes!  They look great to me.  I'll dismiss my request for changes, but I still have to go through the non-FileInput commits.

2020-11-02 18:11 UTC, mikesoltow approved these changes
Looks good from what I can see!

2020-11-02 23:31 UTC, Dhalton approved these changes
Sorry it took so long for me to get around to reviewing this. LGTM!

2020-11-03 19:15 UTC, merged