Footer improvements
repaygithub/cactus pull request #369
Opened 2020-10-24 01:27 UTC by NicolasSimmonds

2020-10-26 17:40 UTC, wilysword approved these changes

2020-10-26 18:55 UTC, mikesoltow requested changes
It looks like this doesn't actually solve the following AC: "On tiny screens, the user must still scroll down to see the Footer if there is enough content to fill the viewport height."

If you look at the Layout story (and the associated visual snapshot) you'll see that content is running off the page, but the footer still displays over some of the text.  To get it to work, you'll need to pass in `flow` to the `useLayout` hook on line 146 in `Footer.tsx`, as that will move the Footer below all content in every instance.

If you do that, you'll also need to change styles in the LogoAndContentSection and LogoWrapper that rely on `.cactus-layout-fixedBottom` to rely on mediaQueries (using `${(p) => media(p.theme, 'small')}`) instead.

2020-10-26 18:55 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +  font-size: 15px;
Can we make this theme-based and pull in the textStyles object?

2020-10-26 18:55 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +    font-size: 15px;
Same here

2020-10-26 18:55 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +  margin-top: auto;
If you change to using the `flow` setting, then I don't think you need this.

2020-10-26 18:55 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> +  flex-direction: column;
If you change to using the `flow` setting, then I don't think you need this.

2020-10-26 18:55 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> +        flex-direction: column;`
If you change to using the `flow` setting, then I don't think you need this.

2020-10-26 18:57 UTC, wilysword commented
@mikesoltow I'd really prefer if we didn't use media queries in these layout components.

2020-10-26 20:41 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> +        flex-direction: column;`
Failure...ignore this

2020-10-26 20:41 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> +  flex-direction: column;
I need to re-learn how to read.  Please ignore this.

2020-10-26 20:42 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +  margin-top: auto;
So much shame.  Ignore this.

2020-10-26 21:17 UTC, mikesoltow reviewed
@NicolasSimmonds Changes look good, but you'll want to merge in `master` and update the visual snapshots.  The line height made a slight change to the footer, I think.

2020-10-28 15:46 UTC, mikesoltow approved these changes
🎉

2020-10-28 15:47 UTC, merged