feat(cactus-web): add dividers option to table and Datagrid components
repaygithub/cactus pull request #374
Opened 2020-10-27 21:10 UTC by NicolasSimmonds

Test:

There is a knob in the Table: layout and DataGrid: basic-usage for you to activate the Dividers on the components.

[CACTUS-395]

2020-10-27 23:03 UTC, wilysword requested changes

2020-10-27 23:03 UTC, wilysword commented on modules/cactus-web/src/Table/Table.tsx
> +      border-right: ${(p): string => (p.dividers ? border(p.theme, 'white') : '')};
This overrides the border on the last cell in the row, which makes it uneven because the table border is still supposed to be uniformly `lightContrast`. Aside from that, this looks good (although personally I find the alternating colors to be a little trippy).

2020-10-28 14:30 UTC, NicolasSimmonds commented on modules/cactus-web/src/Table/Table.tsx
> +      border-right: ${(p): string => (p.dividers ? border(p.theme, 'white') : '')};
Yeah I also think it looks weird, and also the hover state for the rows.

2020-10-29 17:30 UTC, wilysword approved these changes

2020-10-29 20:41 UTC, mikesoltow approved these changes
LGTM!

2020-10-29 20:43 UTC, merged