CACTUS-393 More Footer/Layout Changes
repaygithub/cactus pull request #376
Opened 2020-10-30 22:06 UTC by wilysword

https://repayonline.atlassian.net/browse/CACTUS-393

The first commit fixes a layout/styled-components bug I noticed while working on the footer; I included it here because I originally thought I'd need it to implement the footer changes (though that turned out not to be the case). The second commit is the fixes specific to the ticket.

One thing I noticed when testing in IE: when I changed the viewport it would look like the styles were wrong, but then I opened up the console and unchecked then re-checked a style and the page would reflow correctly. Not sure if that's a BrowserStack issue, and IE issue, or something else.

2020-11-02 19:10 UTC, mikesoltow requested changes
Looks pretty good for the most part.  Just a couple of minor things, plus a humble request to help my brain that can't read code.

2020-11-02 19:10 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
By removing the flex styling here, there's a regression from Nicolas's change to ensure that the footer is rendered at the bottom of the page if there's not enough content.

![Screen Shot 2020-11-02 at 1 29 47 PM](https://user-images.githubusercontent.com/46460514/97908655-fa404700-1d14-11eb-8871-64573b01c9cd.png)

2020-11-02 19:54 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
Random thought: it might be worth having a story that generates a screenshot similar to this so that we have a test case, but I'll leave that up to you.

2020-11-02 20:05 UTC, wilysword commented on modules/cactus-web/src/Footer/Footer.tsx
> +  overflow-wrap: anywhere;
`break-word` doesn't work for me in Firefox (for some reason, which is odd because I'm fairly certain I've seen it work in other places). I will change from `word-break` to `word-wrap`, though.

2020-11-02 20:09 UTC, wilysword commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
You're right, I must not have tested it again after removing this. However, when I have long content and `display: flex;`, I get this:
![footer-overlap](https://user-images.githubusercontent.com/7714951/97914037-7a15e380-1d0c-11eb-81ea-c6051c1177f3.png)

Does that happen to you as well on IE? If so, do you have any idea how to fix it (without breaking anything else)?

2020-11-02 21:53 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
Ugggh, of _course_ it does that.  I'll tinker with this for a bit and see if I can come up with anything.

2020-11-02 22:21 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
I can't seem to tell if that's an issue with viewport resizing or something legit.  Every time I refresh after resizing the screen, I get an "unspecified error" from some Storybook file.

In any case, one thing I _did_ have to do was add `-ms-grid-row-align: center;` to `gridCell2` in `Footer.tsx`, as the alignment was off.

2020-11-02 22:23 UTC, mikesoltow commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
If it is legit, I just wonder if IE isn't dynamically updating the footer position for some reason (is it keeping the footer in the same place vertically as it was in the last viewport?).  I have to run now, but I can look at this more tomorrow if you'd like.

2020-11-03 18:07 UTC, wilysword commented on modules/cactus-web/src/Layout/Layout.tsx
> -  flex-direction: column;
I think I got it working using grid instead of flex.

2020-11-03 22:05 UTC, mikesoltow requested changes
Changes looked great...until I looked at Safari 😭   The short content story looked like the following screenshot:

![Screen Shot 2020-11-03 at 4 57 26 PM](https://user-images.githubusercontent.com/46460514/98044972-c4bf5a80-1df5-11eb-904d-4e48f5e1cb9a.png)

It appears that Safari needs the parent div (i.e. `wrapperStyle`) to have a defined height set.  Why, I'm not sure exactly, but this SO answer is what led me down this road: https://stackoverflow.com/a/44773109.  You can add `height: 100vh` to `wrapperStyle` unless you're on a tiny screen, in which case you have to subtract `60px` for the bottom nav bar.  I didn't _thoroughly_ test everything after adding that, but I think it looked good.

Sorry that browsers suck 😞

2020-11-04 19:46 UTC, mikesoltow approved these changes
Changes look good. Thanks!

2020-11-06 17:59 UTC, Dhalton approved these changes
Sweet! Looks great to me 💯

2020-11-06 18:28 UTC, merged