CACTUS-409 Portal Removal
repaygithub/cactus pull request #399
Opened 2020-11-16 23:34 UTC by wilysword

https://repayonline.atlassian.net/browse/CACTUS-409

It should work almost exactly the same. The major difference is in the "many options" story for the Select component: before it would overlap the drop-down button if it couldn't fit on the screen; currently I have it just stay below. There's a max-height of 400px on the drop-down so unless there's a rather odd set of display conditions, I don't think there would be many situations where you couldn't scroll either up or down to get the whole thing in view. All the same, I'm open to suggestions on how/if we should handle that situation differently.

PS Naming the branch as I did amused me more than it probably should have.

2020-11-17 19:37 UTC, mikesoltow reviewed
Looking pretty good for the most part, although I still need to test on non-Chrome browsers.

Before I did that, however, I wanted to leave a suggestion for the long list of options story.  I was able to create several cases where I couldn't scroll all the way down, so I think it's definitely possible that we'd run into issues.  What if we dynamically changed maxHeight to the remaining space in the viewport below the anchor?  That way it never(? -- Not sure if fixed footers, etc. would cause issues) flow past the bottom of the screen.  I left a rough idea of potential code in the comments.

2020-11-17 19:37 UTC, mikesoltow commented on modules/cactus-web/src/helpers/positionPopover.ts
> +  }
What if we deleted the `max-height` defined in `Select.tsx` and changed this section to:

```suggestion
  if (expectedBottom > maxBottom && expectedTop > 0) {
    const styleBottom = maxBottom + MARGIN - top
    dd.style.top = ''
    dd.style.bottom = `${styleBottom}px`
    dd.style.maxHeight = `${view.clientHeight - styleBottom - 10}px`
  } else {
    const styleTop = bottom + MARGIN
    dd.style.bottom = ''
    dd.style.top = `${styleTop}px`
    dd.style.maxHeight = `${view.clientHeight - styleTop - 10}px`
  }
```

2020-11-17 21:25 UTC, mikesoltow requested changes
Actually I did find one regression we should probably look at.

2020-11-17 21:25 UTC, mikesoltow commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
Looks like there is a small regression here.  If you have a dropdown open on a multi-select and start checking items, then the anchor element changes size, but the dropdown menu no longer changes size with it.  Looks like that was triggered by this `Rect` component that observed the anchor element (when the list was open).  If we don't want to use the `Rect` component, then we may want to make use of `@reach/observe-rect`, which `Rect` uses under the hood (see https://github.com/reach/reach-ui/blob/develop/packages/rect/src/index.tsx#L137).

2020-11-20 17:17 UTC, wilysword commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
To be honest, I'm not sure we should be allowing the select to change size like that in the first place. This should be doable, though.

2020-11-20 17:18 UTC, mikesoltow commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
I assume you're talking about the entire Select and not just the dropdown?  That could be something we look into in a tech debt ticket if you'd like.

2020-11-20 17:24 UTC, wilysword commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
In general I think it's best to avoid changing an element's size, but I'm also not sure how we could keep it the same size while still sizing correctly for dynamic content (e.g. translations). This particular element is probably an exception to that general rule.

2020-11-20 21:19 UTC, wilysword commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
While I talked myself out of my initial concern with the anchor element resizing, I'm still not sure I want to change this back to how it was: it's one thing for an element to resize when your focus is somewhere else, but this would change the width of the container the user is currently clicking in. Try, for instance, opening the drop-down and unchecking elements by clicking near the checkbox on the left side: as the anchor shrinks, you have to keep moving the mouse over and if you were going quickly, would quite likely accidentally close the drop-down. In that respect, I think the new behavior is better than the old behavior.

2020-11-23 23:03 UTC, mikesoltow commented on modules/cactus-web/src/Select/Select.tsx
> -        <Rect observe={isOpen}>
Fair enough.  After playing around with this some more, I'm fine the way you have it.

2020-11-23 23:10 UTC, mikesoltow reviewed
Thanks for the updates regarding the dropdown height for long lists.

I did notice another bug: if you have a mult-select element that takes up the full viewport but then uncheck an item or two, the drop-down will not be correctly aligned with the Select element when first opened.

![Screen Shot 2020-11-23 at 6 04 45 PM](https://user-images.githubusercontent.com/46460514/100025401-afb36700-2db6-11eb-84ac-ae32280c2058.png)

It looks like in this case it's hitting the `  if (expectedRight > maxRight) {` of the `positionDropDown` function in `positionPopover.ts`.  I need to run, unfortunately, and can't dig into it anymore tonight, but I'm wondering if the `ddWidth` isn't what we expect the first time it opens.  In the screenshot of my console below, I logged the values of several variables.  Under "uh oh" are the values for the first toggle, when the list is not properly aligned.  I then close the list and re-open it, and this time it hits the `else` block and logs "all good".  You can see that `ddWidth` is smaller the second time around, which allows it to hit the `else` block.

![Screen Shot 2020-11-23 at 6 05 02 PM](https://user-images.githubusercontent.com/46460514/100025574-10db3a80-2db7-11eb-84d8-0d33bf70f337.png)

2020-11-23 23:20 UTC, wilysword commented
Yeah, that's because the width is calculated based on the _current_ min/max values, which would have been set when the anchor was wider. Once the min is lowered the auto-width is also lowered, but that doesn't happen till the calculations are already done, which is why I have the recursive call at the bottom. I guess it doesn't work as well for shrinking the drop-down as it does for growing it, though, so I'll have to see if I can figure out a way to do that.

2020-11-26 15:08 UTC, NicolasSimmonds approved these changes
Latest changes seem good to me!

2020-12-01 17:38 UTC, Dhalton approved these changes

2020-12-01 19:51 UTC, mikesoltow approved these changes
Thanks for the changes!  LGTM once the conflict is fixed.

2020-12-01 20:43 UTC, merged