Cactus 421 left justified tootlip
repaygithub/cactus pull request #411
Opened 2020-11-25 21:43 UTC by NicolasSimmonds

Test: in the storybok, go to all the *Field components, the CheckBoxGroup and RadioButtonGroup. There is a alignTooltip knob. Toggle between left and right and check it works as expected.

 
[CACTUS-421]

2020-11-30 19:41 UTC, wilysword requested changes
Functionality seems fine, but there's a nitpick with fieldset/legend that _could_ affect accessibility. I also have a suggestion on spacing, but I'm open to discussion on that one.

2020-11-30 19:41 UTC, wilysword commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> +    padding-right: ${(p) => (p.alignTooltip === 'right' ? '28px' : '5px')};
I don't see any reason to have a different rule depending on the tooltip alignment; I'd suggest changing this to a flat 8px for both alignments (second opinions?).

2020-11-30 19:41 UTC, wilysword commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> -    right: 8px;
I think we still need this spacing, try adding `padding-right: 8px`.

2020-11-30 19:41 UTC, wilysword commented on modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.tsx
> +          <Label id={labelId} as="legend">
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend), the `legend` element must be the first child of the `fieldset`, so you can't have the intermediate flex div. You could probably get the same effect by putting the Tooltip inside the Label and changing the Label's display to flex.

2020-11-30 19:41 UTC, wilysword commented on modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.tsx
> +    padding-right: ${(p) => (p.alignTooltip === 'right' ? '28px' : '5px')};
duplicate line

2020-11-30 19:41 UTC, wilysword commented on modules/cactus-web/src/RadioGroup/RadioGroup.tsx
> +          <Label id={labelId} as="legend">
Same thing as with CheckBoxGroup.

2020-11-30 19:57 UTC, NicolasSimmonds commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> +    padding-right: ${(p) => (p.alignTooltip === 'right' ? '28px' : '5px')};
I agree with you

2020-11-30 20:29 UTC, NicolasSimmonds commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> -    right: 8px;
So you are saying leaving the `position: absolute` and `right: 8px`. and also adding the` padding-right: 8px`?

Because with the position absolute the problem is that is hard to align the tooltip exactly at the right of the label

2020-11-30 20:32 UTC, wilysword commented on modules/cactus-web/src/AccessibleField/AccessibleField.tsx
> -    right: 8px;
No, the things you removed here are fine; I meant that you need to add the `padding-right` _in place of_ the `right`. Accomplish the same thing visually, but in a different way.

2020-12-01 18:22 UTC, Dhalton commented
LGTM but it looks like there are a lot of conflicts so I'll wait to approve.

2020-12-01 21:13 UTC, wilysword commented
I think you had the wrong version of `cactus-theme` when you updated the snapshots/storyshots, they're showing round corners instead of intermediate.

2020-12-02 17:05 UTC, wilysword approved these changes

2020-12-02 17:49 UTC, Dhalton approved these changes

2020-12-02 21:08 UTC, merged