docs(cactus-web): add clarification to actionbar and layout docs
repaygithub/cactus pull request #413
Opened 2020-11-27 18:58 UTC by NicolasSimmonds

Check the docs page for Actionbar and Layout, and see the docs are good now

[CACTUS-423]

2020-11-30 18:56 UTC, wilysword requested changes

2020-11-30 18:56 UTC, wilysword commented on modules/cactus-web/src/ActionBar/ActionBar.mdx
> +      //Action bar options
```suggestion
      // Global action bar options
```

2020-11-30 18:56 UTC, wilysword commented on modules/cactus-web/src/ActionBar/ActionBar.mdx
> +)
This is just what I had in mind for the example, but I think it would work better if you moved it up to be part of the code on lines 76-85, with comments separating the two "files": something like
```
// MyPage.tsx
import React from 'react'
Rest of the example, etc.
  </>
)

// App.tsx
the rest of your new example
```
That makes it clearer that the two examples are related.

2020-11-30 18:56 UTC, wilysword commented on modules/cactus-web/src/Layout/Layout.mdx
> +Also, we use `@reach/router` in this example, but you are free to use any routing library that you want.
I don't think you need to specifically mention that the components are made-up. You should probably mention that depending on the library, the MenuBar may also need to be connected to the Router so that links will work; in fact, you should probably update the `MenuBar.Item`s in this example so they're linked to the sample content pages.

Also @mikesoltow I know bytemover isn't using `@reach/router`, is there a routing library we recommend?

2020-12-01 21:43 UTC, wilysword reviewed
Just a couple more clarifications.

2020-12-01 21:43 UTC, wilysword commented on modules/cactus-web/src/ActionBar/ActionBar.mdx
> +// App.tsx
Move this up four lines, above the imports.

2020-12-01 21:43 UTC, wilysword commented on modules/cactus-web/src/Layout/Layout.mdx
> +        <Router>
I think the `<Router>` element needs to go outside the `Layout` so the MenuBar links will work, like
```
<Router>
  <Layout>
    ...etc
    <Layout.Content>
      <Switch>
        ...etc
      </Switch>
    </Layout.Content>
  </Layout>
</Router>
```

2020-12-01 21:43 UTC, wilysword commented on modules/cactus-web/src/Layout/Layout.mdx
> +        </MenuBar.Item>
```suggestion
        <MenuBar.Item as={Link} to="/home">Teenage Mutant</MenuBar.Item>
        <MenuBar.Item as={Link} to="/other/path">Ninja Turtles</MenuBar.Item>
```

2020-12-01 21:47 UTC, NicolasSimmonds commented on modules/cactus-web/src/Layout/Layout.mdx
> +        <Router>
Well I tested this on the generated app from our cli and it worked this way. But if you prefer it outside `Layout` I'm happy to do it

2020-12-04 20:43 UTC, Dhalton approved these changes
LGTM -- looks like you do have merge conflict though.

2020-12-07 16:47 UTC, wilysword approved these changes

2020-12-07 17:00 UTC, merged