CACTUS-418: blacklist stories for visual testing
repaygithub/cactus pull request #414
Opened 2020-11-30 20:13 UTC by NicolasSimmonds

[CACTUS-418]

2020-11-30 21:15 UTC, wilysword requested changes
In Select.story.tsx, I think we could also remove the `Long option labels` storyshot.

I like that you changed the modals to default open, makes those storyshots much more meaningful.

2020-11-30 21:15 UTC, wilysword commented on modules/cactus-web/src/Button/Button.story.tsx
> +AsLink.parameters = { storyshots: false }
I actually think we should keep this one. It does look just the same as the others, but because `<a>` has different default browser styles than `<button>`, I think the storyshot has value in case we accidentally remove something that makes them look the same.

2020-11-30 21:15 UTC, wilysword commented on modules/cactus-web/src/SelectField/SelectField.story.tsx
> +CustomStyles.parameters = { storyshots: false }
Should this be on `ControllerForm` instead? That and `BasicUsage` look identical to me, but `CustomStyles` is slightly different. (Though it's not _that_ different, so maybe we should just disable both.)

2020-12-01 16:58 UTC, wilysword approved these changes

2020-12-01 19:25 UTC, Dhalton approved these changes
LGTM 👍

2020-12-01 19:38 UTC, merged