CACTUS-429: allow configurable text for empty optins in select
repaygithub/cactus pull request #421
Opened 2020-12-04 15:59 UTC by NicolasSimmonds

In the Select story, basic usage there is a knob to disable the option. If it's false the text "No options available" should be displayed.

In WithCombobox there is the same knob, but for it to show the no options available text, the **canCreateOption** knob should also be disabled.

[CACTUS-429]

2020-12-04 20:13 UTC, mikesoltow requested changes
Looks good.  Just one little requested change.

Also, while I know this isn't in the scope of your ticket, I noticed that the no options text can bump right up to the down-arrow icon in a way that looks awkward.  Would you mind adding a little more padding to `SelectTrigger`?  I'd say your best bet is changing line 254 from `padding: 0 24px 0 16px` to `padding: 0 28px 0 16px', unless you can think of a better solution.

2020-12-04 20:13 UTC, mikesoltow commented on modules/cactus-web/src/Select/Select.tsx
> +  noOptionsText?: string
Can you add this to `propTypes` as well?  We should probably also add a `defaultProp`

2020-12-04 22:25 UTC, mikesoltow approved these changes
Thanks, Nicolas!

2020-12-07 17:24 UTC, wilysword approved these changes

2020-12-07 18:09 UTC, merged