CACTUS-426: convert some knobs to multi-stories
repaygithub/cactus pull request #429
Opened 2020-12-08 19:34 UTC by NicolasSimmonds

These are the components that change In storybook:

- AccessibleField
- Alert
- Avatar
- Button
- Card
- CheckBoxField
- DateInputField
- FileInputField
- Footer
- IconButton
- MenuButton
- PrevNext
- RadioButtonField
- SelectField
-  SplitButton
- TextAreaField
- Textbutton
- TextInputField
- ToggleField
- Tooltip 

[CACTUS-426]

2020-12-09 17:44 UTC, Dhalton requested changes
Overall it's lookin' pretty good but I think there are a few areas where we could improve the scope of what will be tested visually.

2020-12-09 17:44 UTC, Dhalton commented on modules/cactus-web/src/AccessibleField/AccessibleField.story.tsx
> +export const DifferentVariants = (): React.ReactElement => (
What's the reason for putting these in a separate story instead of just putting them in the basic usage story?

2020-12-09 17:44 UTC, Dhalton commented on modules/cactus-web/src/AccessibleField/AccessibleField.story.tsx
> +    <span>Disabled</span>
Could we just get rid of these spans, take the text from each one and use the field label to denote what vriant is being displayed? I think that'd clean it up a bit

2020-12-09 17:44 UTC, Dhalton commented on modules/cactus-web/src/IconButton/IconButton.story.tsx
> +        variant={select('variant', iconButtonVariants, 'standard')}
I think we should render each of these variants instead of keeping the knob here

2020-12-09 17:44 UTC, Dhalton commented on modules/cactus-web/src/MenuButton/MenuButton.story.tsx
> +      variant={select('variant', ['filled', 'unfilled'], 'filled')}
I think we should render a `filled` and `unfilled` variant separately in this story too

2020-12-09 17:44 UTC, Dhalton commented on modules/cactus-web/src/SplitButton/SplitButton.story.tsx
> +        variant={variant}
There are multiple variants here that I think we should split out as well

2020-12-09 19:48 UTC, NicolasSimmonds commented on modules/cactus-web/src/AccessibleField/AccessibleField.story.tsx
> +export const DifferentVariants = (): React.ReactElement => (
They looked a little bit weird. But the main reason is that on tiny screen the tooltip was covering the input field so you couldn't see what you were typipng

2020-12-10 19:48 UTC, Dhalton commented on modules/cactus-web/src/AccessibleField/AccessibleField.story.tsx
> +    <AccessibleField warning="Warning message" label="waring Message" name="field_name">
Typo here on the label

2020-12-10 19:50 UTC, Dhalton approved these changes
Thanks for making those changes! They look good for the most part -- there's a typo that I mentioned but I'll still approve it.

2020-12-11 17:14 UTC, mikesoltow requested changes
Thanks for doing this!  I have two major comments:

1. I know we discussed adding labels to the various variants, but it looks like there are a few more places you can do that.  When I highlighted an opportunity, it's more of a request to see if you can make it work, rather than a blocker, as I know it could be tricky to get labels to fit for some of the stories in mobile mode.
2. It looks like some of the screenshots, particularly the desktop variants, didn't update to reflect the changes you made to the stories.  The changes must have been under the failure threshold.  If `yarn test:docker-update` doesn't update them, then I'd recommend deleting the relevant screenshots (all three screen sizes) and then re-running it.

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.story.tsx
> +    <div>
Can you make the width 100%?  The story looks a little weird with footers that don't take up the entire width.

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/IconButton/IconButton.story.tsx
> +const IconButtonBase = ({ variant }: { variant: IconButtonVariants }) => {
Would it be possible to add size/variant labels?

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/MenuButton/MenuButton.story.tsx
> +  </div>
Looks like the screenshot (at least for desktop) doesn't match this story.  Can you update the snapshots again to capture your latest changes?

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/PrevNext/PrevNext.story.tsx
> +  </div>
Doesn't look like the screenshot updated for this story either.

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/RadioButtonField/RadioButtonField.story.tsx
> +      label={text('label', 'A Label')}
Change we change this label to "Disabled" or something?

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/SelectField/SelectField.story.tsx
> +  </div>
This screenshot needs to be updated as well.  Also, both variants have knobs with the same name, so the disabled label probably won't show up.

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/SplitButton/SplitButton.story.tsx
>        mainActionLabel={text('mainActionLabel', 'Main Action')}
Can we change the Main Action Label to identify the variant?

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/TextAreaField/TextAreaField.story.tsx
> +      label="Field Label"
Can we change tis label to "Disabled"?

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/TextButton/TextButton.story.tsx
> +  </div>
This screenshot needs to be updated

2020-12-11 17:14 UTC, mikesoltow commented on modules/cactus-web/src/Tooltip/Tooltip.story.tsx
> +  </Flex>
This screenshot needs to be updated

2020-12-14 17:58 UTC, wilysword requested changes
Visually I like all the changes you've made. Code-wise I have a couple of nitpicks, one important change on SelectField, and a bug.

2020-12-14 17:58 UTC, wilysword commented on modules/cactus-web/src/Button/Button.story.tsx
> +        ></Button>
I feel like you didn't mean to make this change, it looks very odd.

2020-12-14 17:58 UTC, wilysword commented on modules/cactus-web/src/SelectField/SelectField.story.tsx
> +    />
I'd recommend swapping the order and putting this one first; because the screenshot opens the drop-down, it completely covers the disabled one. Make sure to change the name from "ufo" to something else, so the `beforeScreenshot` hook will pick the enabled field.

2020-12-14 17:58 UTC, wilysword commented on modules/cactus-web/src/TextButton/TextButton.story.tsx
> +      inverse={boolean('inverse', false)}
This (and maybe some of the others) causes an error when you check the "inverse" knob.

2020-12-14 17:58 UTC, wilysword commented on modules/cactus-web/src/TextButton/TextButton.story.tsx
> +      {text('children', 'Cancel')}
Just like on many of the other stories, could we change the text of the button to indicate which variant it is?

2020-12-14 17:58 UTC, wilysword commented on modules/cactus-web/src/TextInputField/TextInputField.story.tsx
> -BasicUsage.parameters = { cactus: { overrides: { height: '110vh', width: '110vw' } } }
👏

2020-12-14 20:37 UTC, NicolasSimmonds commented on modules/cactus-web/src/TextButton/TextButton.story.tsx
> +      inverse={boolean('inverse', false)}
on TextButton.tsx, line 56, there is an if statement checking if the variant is danger and inverse is true, if that passes, then it throws an error. I think disabling the inverse option for danger would work. What do you think? Also, I did not found other place where this was happening

2020-12-14 23:13 UTC, wilysword commented on modules/cactus-web/src/SelectField/SelectField.story.tsx
> +      label={text('label', `Disabled`)}
Change this to just "Disabled", right now it's overriding the default label on the active SelectField.
```suggestion
      label="Disabled"
```

2020-12-14 23:14 UTC, wilysword commented on modules/cactus-web/src/Button/Button.story.tsx
> +        ></Button>
I don't think the recent change you made here fixes the problem; when I said "it looks odd" I meant the button looks strange visually, not that the closing tag in the code looks odd.

2020-12-15 21:16 UTC, mikesoltow reviewed
Updates look mostly good.  Just one story that needs screenshots updated.

2020-12-15 21:16 UTC, mikesoltow commented on modules/cactus-web/src/TextButton/TextButton.story.tsx
> +      Action
These updates still aren't captured in all the screenshots: just the iPhone 5 version

2020-12-16 18:49 UTC, mikesoltow approved these changes
Thanks, Nicolas!

2020-12-16 20:10 UTC, mikesoltow commented
@wilysword You're still listed as requesting changes, so I'm going to wait for your approval before merging.

2020-12-16 20:24 UTC, NicolasSimmonds commented on modules/cactus-web/src/Button/Button.story.tsx
> +        ></Button>
I hadn't seen this response, sorry. Just updated

2020-12-16 21:35 UTC, wilysword approved these changes

2020-12-16 22:20 UTC, merged