CACTUS-471 :: Getting Started Tutorial
repaygithub/cactus pull request #498
Opened 2021-01-28 21:11 UTC by Dhalton

Ticket: https://repayonline.atlassian.net/browse/CACTUS-471

I'm no tutorial expert, so all suggestions are welcome. I thought about doing something a little more...meaningful inside the cards, but I also wanted to keep it pretty simple so I don't take any attention away from the main focus, which is to build a responsive page using `Grid`.

Let me know what you think!

2021-01-29 20:13 UTC, mikesoltow requested changes
Looks great!  Just a couple of minor things.  Also, can you add a Tutorials section to the sidebar?

Finally, I think our links (not just the one you created) are messed up again.  I'll get another ticket up for this.

2021-01-29 20:13 UTC, mikesoltow commented on docs/Tutorials/Responsive Web Design.md
> +  <div style={{ padding: '16px' }}>
My two cents would be to have them use `Box` here with the `padding` prop, so we can start teaching them that interface.  Not a big deal though.

2021-01-29 20:13 UTC, mikesoltow commented on docs/Tutorials/Responsive Web Design.md
> +Start by creating a lazy version of the component using React's `lazy` function:
I'd clarify that this is going in `App.jsx`

2021-01-29 20:13 UTC, mikesoltow commented on docs/Tutorials/Responsive Web Design.md
> +<Route path="/responsive-page">
```suggestion
<Route path="/favorites">
```

2021-01-29 22:24 UTC, Dhalton commented on docs/Tutorials/Responsive Web Design.md
> +<Route path="/responsive-page">
Dang! I thought I got all of the places that referenced this...I wrote this to be pretty general for my first pass and then decided on renaming some stuff later on. Anyway, nice catch I will get this updated

2021-01-29 22:26 UTC, Dhalton commented on docs/Tutorials/Responsive Web Design.md
> +Install the `@repay/create-ui` CLI by running `yarn global add @repay/create-ui` or `npm add -g @repay/create-ui` in your terminal.
Lol would you like me to remove this? I included it since we can't really know what package manager anyone who's following this tutorial is using

2021-01-29 22:27 UTC, mikesoltow commented on docs/Tutorials/Responsive Web Design.md
> +Install the `@repay/create-ui` CLI by running `yarn global add @repay/create-ui` or `npm add -g @repay/create-ui` in your terminal.
Haha no this wasn't a serious requested change 😄

2021-01-29 22:29 UTC, Dhalton commented on docs/Tutorials/Responsive Web Design.md
> +Install the `@repay/create-ui` CLI by running `yarn global add @repay/create-ui` or `npm add -g @repay/create-ui` in your terminal.
I guess they'd need yarn to start the app they generate anyway, so I could add a little section making sure they have yarn installed already before the tutorial begins

2021-02-01 20:58 UTC, daniloPenaR commented
I think you've done a great job with the new docs. 

When I was reading the docs a couple of days ago I thought that the Getting Started section was too short. But now I think it's ok!

That step-by-step part that you've added to the responsive web design section works well too, I want to highlight that paragraph that explains what the `lazy` function does and finishes with a reference to the React's documentation: This makes the documentation much more complete, cool.

2021-02-01 21:40 UTC, daniloPenaR approved these changes
I think you've done a great job with the new docs.

When I was reading the docs a couple of days ago I thought that the Getting Started section was too short. But now I think it's ok!

That step-by-step part that you've added to the responsive web design section works well too, I want to highlight that paragraph that explains what the lazy function does and finishes with a reference to the React's documentation: This makes the documentation much more complete, cool.

2021-02-02 15:36 UTC, mikesoltow approved these changes
Thanks for the changes.  Looks great!

2021-02-02 15:40 UTC, merged