Cactus 496: Dimmer component
repaygithub/cactus pull request #502
Opened 2021-01-29 22:18 UTC by daniloPenaR

2021-02-01 22:28 UTC, wilysword requested changes

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.story.tsx
> +        <Flex mx={15} justifyContent="start" alignItems="flex-start" flexDirection="column">
The Layout's content needs to go in the `Layout.Content` component, or the styles get thrown off. I actually think you don't need the Layout or BrandBar, though, the Flex alone would do it for all these stories.

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.story.tsx
> +        <Button onClick={() => setOpen(true)}>Activate dimmer!</Button>
When you focus this button and then activate it, the button retains focus meaning that although you can't click it, you can still activate it with the keyboard. When the dimmer opens, it should probably blur the active element (unless the active element is within the dimmer).

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  page?: boolean
Mike and I had a discussion about this page prop (https://repay.slack.com/archives/CABGTU4S3/p1612199551048700), and I think it would be best to remove it (and also remove the `DimmableContent` component). Basically, we don't actually have a use case for that and it's generally best to leave out code that doesn't have a foreseeable use. (If you want to keep it, though, you can wait for a second opinion.)

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  )
If you're going to use the `active` prop to conditionally render, I'd just go with conditionally rendering the whole thing:
```suggestion
  return active && (<DimmerStyled page={page}>{children}</DimmerStyled>)
```

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Modal/Modal.tsx
> +      <ModalPopUp
This isn't working right, because the `ModalPopUp` has it's own built-in overlay. What you need is to get the styles from Dimmer, but apply them to DialogOverlay:
```
export const ModalPopUp = styled(Dimmer).withConfig({
  shouldForwardProp: [omitted for brevity]
})<ModalPopupProps>`
  ...any addtional styles not covered by the Dimmer, etc.
`.withComponent(DialogOverlay)
```
and then put the rest of this code back how it was.

2021-02-01 22:28 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.story.tsx
> +        <Dimmer active={open} page>
You don't need the Dimmer around the Modal component, it should be part of the Modal. You don't need this story at all, in fact, since there are already plenty of stories with modals in them.

2021-02-01 22:37 UTC, Dhalton commented
I was about to submit my review but it looks like Glen beat me to the punch. I was going to mention a lot of the things he did, though, so I'll just +1 everything Glen said 😄

2021-02-02 15:34 UTC, daniloPenaR commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  page?: boolean
Dhalton gave a +1 to everything you said, so, I'm going to remove it hahaha

2021-02-02 22:45 UTC, Dhalton requested changes
Looks much better! Just a couple of things I noticed but I'll be ready to approve when those are taken care of.

2021-02-02 22:45 UTC, Dhalton commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  background: rgba(46, 53, 56, 0.9);
We really should be using the colors from the theme here. It looks like the style guide specifies `darkestContrast`, so the way to set that using the theme would be:
`background: ${(p) => p.theme.colors.darkestContrast};`

2021-02-02 22:45 UTC, Dhalton commented on modules/cactus-web/src/Dimmer/Dimmer.mdx
> +import DateInput from './DateInput'
Looks like this line is preventing the docs site from building. Once this is gone, you can test the docs site by running `yarn docs start` from the root. I'd recommend giving it a quick look over as the docs site tends to operate according to its own rules.

2021-02-02 22:49 UTC, daniloPenaR commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  background: rgba(46, 53, 56, 0.9);
But if I set the Bg on that way and use the `opacity` property, the content will be affected by that opacity too.

2021-02-02 22:49 UTC, daniloPenaR commented on modules/cactus-web/src/Dimmer/Dimmer.mdx
> +import DateInput from './DateInput'
Thanks! I'll check it now.

2021-02-02 23:59 UTC, Dhalton commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  background: rgba(46, 53, 56, 0.9);
Ah, good point. I wonder if it would be worth it to add a new version of `darkestContrast` with this opacity to the theme in the future then. 🤔 Mike, Glen, what do you guys think?

2021-02-03 17:10 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +}
This is redundant with the static attributes on your class.

2021-02-03 17:10 UTC, wilysword commented on modules/cactus-web/src/Dimmer/Dimmer.tsx
> +  }
You don't have to change anything, but just for future reference you can do this in a functional component as well with the `useEffect` hook.
```
const { active } = props
React.useEffect(() => {
  if (active && document.activeElement) {
    ;(document.activeElement as HTMLElement).blur()
  }
}, [active])

2021-02-03 17:15 UTC, wilysword commented
Oh wow, we almost forgot something extremely important: you also need to export this in the `index.ts` file:
```
export { DateInputField } from './DateInputField/DateInputField'
export { default as Dimmer } from './Dimmer/Dimmer'
```

2021-02-05 16:50 UTC, Dhalton approved these changes
LGTM, thanks for making those changes, Danilo

2021-02-08 16:59 UTC, wilysword approved these changes

2021-02-08 17:55 UTC, merged