CACTUS-504 :: ColorPicker
repaygithub/cactus pull request #508
Opened 2021-02-08 23:43 UTC by Dhalton

Ticket: https://repayonline.atlassian.net/browse/CACTUS-504

I had to create a component inline for the palette icon, so we'll definitely want to move that to the icon library after this is merged.

I think there's room for improvement here if we were to update the `TextInput` & `TextInputField` to better support an `as` prop. I didn't want to do that refactoring in this PR, but if we made that possible in the future, we could then do something like `TextInputField as={EditableInput} ... />` instead of doing all of the css for those fields in this component.

Lastly, there is a small issue with Saturation element in IE11; you can't drag the pointer. You can click somewhere on the Saturation element and the pointer will move there, so I don't think it's a huge deal, but I want to point that out. I tried to find some info on it but [this](https://github.com/casesandberg/react-color/issues/795) was the most similar issue I could find and there's no update on it so far.

2021-02-09 17:21 UTC, mikesoltow reviewed
Looks great!  The main thing for me is a question about the Cancel behavior (see the relevant comment in the code).  I'm about to start cross-browser tests, but I wanted to leave you with the feedback I have so far first.

For the screenshots, should we have it click the button to open the popup before the screenshot is taken?

2021-02-09 17:21 UTC, mikesoltow commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +    setOpen(false)
In addition to closing the popup, don't we also need to reset the state to where it was?  Otherwise, the value has changed, but `onChange` was never triggered.

2021-02-09 17:49 UTC, mikesoltow reviewed
Cross-browser testing looked good.  Just one additional comment regarding a console warning I saw.

2021-02-09 17:49 UTC, mikesoltow commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  }
I noticed this console warning generated by `styled-components`:

```
Over 200 classes were generated for component styled.div with the id of "sc-exqJjn".
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs(props => ({
    style: {
      background: props.background,
    },
  }))`width: 100%;`

  <Component />```
  
  Perhaps we want to control `background-color` with `attrs` instead?

2021-02-09 17:51 UTC, mikesoltow commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +    setOpen(false)
I noticed afterwards that this weird behavior only happens on the uncontrolled version (since the `useEffect` hook only resets the value if one was passed in).  I still think it would be nice to reset the value, however, as otherwise Cancel and Apply aren't really different from each other in the uncontrolled case.

2021-02-09 17:59 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
What exactly is an EditableInput and why are we using it here? From what I'm seeing it doesn't seem to add anything over a regular input.

2021-02-09 18:02 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +    setOpen(false)
Ah yeah you're right. I was mostly using the "Controlled" story so that's probably why I missed it. Thanks for letting me know. I will update this today

2021-02-09 18:03 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  }
Hmmmm 🤔 do you know how this was triggered? Haven't seen this...I'll see if I can figure out how to reproduce it.

2021-02-09 18:05 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.story.tsx
> +    console.log(e.target.value)
The value is an object so when I concatenated it with the string it just logged out "[Object] [object]" or something like that

2021-02-09 18:05 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  }
Why change the background color at all? Maybe instead have the element with a transparent background color, and a very thick border + solid outset box shadow?

2021-02-09 18:06 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +        >
No real reason other than the fact that I didn't realize it was there and that I should. 😉 I'll update it to use the helper

2021-02-09 18:08 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.story.tsx
> +    console.log(e.target.value)
You don't have to concatenate, you could log it like
```
console.log(`onChange '${e.target.name}':`, e.target.value)
```
However, now that I realize the `value` is a complex nested object, I suppose it's probably more readable to have it on a separate line.

2021-02-09 18:09 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  }
Whoa...mind = blown 🤯. That's a good idea, Glen. I'll give that a shot.

2021-02-09 18:11 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
From the [docs](https://casesandberg.github.io/react-color/)...

> Use EditableInput to display an input / label that acts as the single source of truth until the input is blurred.

I felt I needed to use it because of that bit about it acting as the single source of truth until it's blurred, but honestly it was a pain to work with. Maybe I could try to pull off the same behavior using our inputs...I will try.

2021-02-09 18:14 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +        >
Alright, to keep the behavior similar to how it is now, you'll probably want to ignore most if not all of the `wrapperProps`.

2021-02-09 18:17 UTC, Dhalton commented
> Would it make more sense to put the palette icon on the left, like with the date picker?

Yeah we could do that. I was going off of the design but as the ticket says it doesn't have to be exact. I'll run the idea by the designers and see what they think.

2021-02-09 18:26 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
I don't even understand what that means, and [looking at the code](https://github.com/casesandberg/react-color/blob/master/src/components/common/EditableInput.js#L59) it still fires `onChange` events normally. Since browsers only allow a single input to have focus, don't _all_ inputs become the single source of truth while they're focused? The user, at least, can't make any other changes.

2021-02-09 18:32 UTC, wilysword commented
Not sure why, but when I change the color by typing in the main input (popup closed): as you said it doesn't fire `onChange` unless the value is valid, but it's firing the event with the _previous_ valid value.

2021-02-09 18:38 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +        const cactusEvent = new CactusChangeEvent(eventTarget, event)
Here's the problem. The box will update the target value on the next render, but you're raising the event right away so you'll need to manually update the value here.

2021-02-09 18:44 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +        const cactusEvent = new CactusChangeEvent(eventTarget, event)
Thank you for pointing this out, appreciate it. That could've been bad!

2021-02-09 18:44 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
Okay, looking at it a bit more I think all it really means is that it ignores the `value` prop while it's focused, so it's like a Frankenstein controlled & uncontrolled input. I'm not sure that's a good idea, personally, but you can do whatever's easiest.

2021-02-09 21:53 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
So I've been experimenting with this and I think we are going to have to leave them as `EditableInput`s. We need that hybrid controlled/uncontrolled behavior. Take a hex input for example: If I try to use a native HTML `input`, there are two ways to go about writing the change handler, but only one would work as far as I can tell:

1. I update the state immediately on change, but then I'm left with an invalid value and no way to update it since every change I try to make just keeps generating invalid color values.
2. I wait for the hex value to be valid before updating the state, but that would mean I still need to ignore the value passed to the input until either the hex value is valid or the input is blurred, otherwise there's no way to type in the input b/c the state isn't updating and the value is therefore not changing.

So I'd still have to implement the exact same behavior that the `EditableInput` does.

2021-02-09 22:07 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +          <EditableInput
I think the problem with (1) is that you're trying to use a single state value to be two things: the state of the text input, _and_ the state of the color picker as a whole. Like I said, though, however is easiest for you I'm fine with.

2021-02-10 17:23 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +      toggle(true, hexInput)
This focus hint isn't working in the story because it's selecting the input from the disabled color picker. You should harden the selector so it'll work even if multiple pickers are on the page, e.g.
```
const hexInput = document.querySelector(`#${popupProps.id} input`)
```

2021-02-10 17:24 UTC, wilysword commented
I think you need to manually delete the extra storyshots you generated before.

2021-02-10 17:26 UTC, mikesoltow reviewed
Just a few more minor comments

2021-02-10 17:26 UTC, mikesoltow commented on modules/cactus-web/src/ColorPicker/ColorPicker.test.tsx
> +      expect(onChange).not.toHaveBeenCalled()
It might also be a good idea to add an assertion here to verify that the value was reset

2021-02-10 17:26 UTC, mikesoltow commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  const [openedState, setOpenedState] = useState<Color>(initialState)
I wonder if this should be a ref?  Not sure we need to re-render when we change it.

2021-02-11 17:48 UTC, mikesoltow requested changes
Change look good, but found one little styling hiccup.  If you type in CCCCCC into the input field, then the text is wider than the input (see screenshot).  Increasing the input's width from 4.5 to 5 rem seemed to fix it.
![Screen Shot 2021-02-11 at 12 43 04 PM](https://user-images.githubusercontent.com/46460514/107676653-5fd29680-6c67-11eb-893d-76a0bcbc88cb.png)

2021-02-11 21:07 UTC, wilysword commented
I think we're almost there, but there's still something funky going on with the cancel. To reproduce:

1. Type something in the main hex input, it fires the change event
2. Shift+tab to the icon button, space to activate
3. Use the mouse to pick a random hue/saturation
4. Press the cancel button, and the value goes back to what it was _before_ step one. (Only the value in the input, a change event is not fired.)
5. If in step two you use the mouse to open the picker instead of the keyboard, cancel will restore to the correct value.

2021-02-11 21:33 UTC, Dhalton commented
@wilysword There you go saving my butt again...thanks for pointing that out. Should be working now

2021-02-11 21:51 UTC, wilysword approved these changes

2021-02-12 18:46 UTC, mikesoltow reviewed
Looking good.  Just one more thing on IE11 (see screenshot).  I think you can get rid of that by ditching the `height: 478px;` line in `ColorPickerPopup`

2021-02-12 18:47 UTC, mikesoltow commented
Just realized I didn't actually upload the screenshot.  Here you go.

![Screen Shot 2021-02-12 at 1 27 27 PM](https://user-images.githubusercontent.com/46460514/107809243-c378c480-6d38-11eb-8a4c-ecd9a04fd897.png)

2021-02-15 18:11 UTC, mikesoltow approved these changes
LGTM

2021-02-15 18:12 UTC, merged