Cactus 532: Divider Component
repaygithub/cactus pull request #537
Opened 2021-03-02 12:28 UTC by daniloPenaR

[CACTUS-532](https://repayonline.atlassian.net/browse/CACTUS-532)

This component is pretty simple. If I missed something, please let me know.

2021-03-02 19:48 UTC, Dhalton reviewed
LGTM but I just have a question I wanted to ask the rest of the team before I approve

2021-03-02 19:48 UTC, Dhalton commented on modules/cactus-web/src/Divider/Divider.tsx
> +export const Divider = styled.hr`
Something I just though of: We support the margin props on pretty much all of our components, so should we also add support for them here? I could see that being useful. Looking for opinions on this, though. What do you guys think?

2021-03-02 20:11 UTC, mikesoltow commented on modules/cactus-web/src/Divider/Divider.tsx
> +export const Divider = styled.hr`
I'm not opposed to adding that in.  I think that, in general, I would prefer that the width be constrained by the parent's padding than the divider's margin...but it doesn't hurt to add it in just in case.

2021-03-02 20:34 UTC, mikesoltow requested changes

2021-03-02 20:34 UTC, mikesoltow commented on modules/cactus-web/src/Divider/Divider.tsx
> +  border: ${(p) => border(p.theme, 'lightContrast')};
This line looked thicker than 1px to me, so I did some digging and found this: https://stackoverflow.com/questions/4151743/how-can-i-change-the-thickness-of-my-hr-tag

Basically it recommends changing this to the following.

```suggestion
  border: none;
  height: ${(p) => p.border === 'thin' ? '1px' : '2px'};
  color: ${(p) => p.theme.colors.lightContrast};
  background-color: ${(p) => p.theme.colors.lightContrast};
```

The attached screenshot shows both the new styles (top divider) and the styles as you have them (bottom divider).  Notice how the new styles are thinner.

<img width="298" alt="Screen Shot 2021-03-02 at 3 28 16 PM" src="https://user-images.githubusercontent.com/46460514/109711105-7c7a3400-7b6c-11eb-8119-309d7ce56315.png">

2021-03-03 21:20 UTC, Dhalton approved these changes
LGTM, nice work!

2021-03-03 21:56 UTC, mikesoltow approved these changes
LGTM

2021-03-03 22:18 UTC, merged