CACTUS-544 :: Notification Component
repaygithub/cactus pull request #550
Opened 2021-03-15 20:18 UTC by Dhalton

Ticket: https://repayonline.atlassian.net/browse/CACTUS-544

### Testing
Open the Notification "Basic Usage" story and make sure the alert is positioned where it's supposed to be when you change the values of the knobs.

2021-03-16 14:31 UTC, daniloPenaR approved these changes
Nice work

2021-03-16 17:19 UTC, wilysword requested changes
The third one is the "requested change", the other two are just suggestions.

2021-03-16 17:19 UTC, wilysword commented on modules/cactus-web/src/Notification/Notification.story.tsx
> +    await page.click('button[id="open-notification"]')
I don't know if the ID selector is actually more efficient, but 🤷.
```suggestion
    await page.click('#open-notification')
```

2021-03-16 17:19 UTC, wilysword commented on modules/cactus-web/src/Notification/Notification.tsx
> +  position?: Position
What's the reasoning for having this be an object instead of two separate props? Personally, I think `<X vertical="top" horizontal="left" />` is both easier to read and looks better than `<X position={{ vertical: 'top', horizontal: 'left' }} />` (the double brackets annoy me for some reason, same when I have to use the `style` prop). If you don't like just calling them `horizontal` and `vertical`, maybe `positionX` & `positionY`.

2021-03-16 17:19 UTC, wilysword commented on modules/cactus-web/src/Notification/Notification.tsx
> +  }
😕 ❓ These aren't exactly CPU-intensive calculations, why are you making functions for them instead of calculating directly? For the second one especially, it might be better to  just pass the screen size as a prop and do the calculation in `getNotificationPosition`: then you could reference `theme.space` instead of hard-coding pixel numbers. (I admit I hard-code pixels way too much, I really need to get better at that...)

2021-03-16 17:32 UTC, Dhalton commented on modules/cactus-web/src/Notification/Notification.tsx
> +  position?: Position
This was how it was stubbed out in the suggested API on the ticket but I don't have a problem making it two props.

2021-03-16 17:33 UTC, Dhalton commented on modules/cactus-web/src/Notification/Notification.tsx
> +  }
It just felt cleaner to keep them in functions instead of in the body of the component. I like your suggestion for using `theme.space`, though. Will update.

2021-03-17 17:05 UTC, wilysword approved these changes

2021-03-17 17:52 UTC, merged