Cactus 521 : Header Component
repaygithub/cactus pull request #551
Opened 2021-03-15 20:27 UTC by daniloPenaR

[CACTUS 521](https://repayonline.atlassian.net/browse/CACTUS-521)

Let me know how can I achieve a better typification of the components or subcomponents, if necessary. I typed many parameters as `any`.

2021-03-15 21:46 UTC, mikesoltow requested changes
Looks pretty good for the most part, but there are a few tweaks we might want to make.  Most of my comments are up to you, but there are a couple of things we should definitely fix (mobile padding-top, vertical alignment of Header.Items).

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +          (child: any) => child.type.displayName === 'HeaderBreadcrumbRow' && <>{child}</>
To avoid the `any` here, you could do the following if you want.  First try adding the following two lines above line 41:

```typescript
type ChildType = React.ReactChild | React.ReactFragment | React.ReactPortal
type ChildElement = React.ReactElement<any, React.ComponentClass | React.FunctionComponent>
```

Then, you can change this line to the following:

```suggestion
          (child: ChildType) =>
            (child as ChildElement).type.displayName === 'HeaderBreadcrumbRow' && <>{child}</>
```

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +  children?: ReactNode
You shouldn't need to specify `children` here, as it's already provided by `React.FC`.

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderItem: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({ children }) => {
The type signature here is not valid.  Since this element is not a div, it shouldn't accept div props.  If you want it to render a div, you could change it to simply: `export const HeaderItem: React.FC<React.HTMLAttributes<HTMLDivElement>> = (props) => <div {...props} />`.  If not, then I'd change this to:

```suggestion
export const HeaderItem = ({ children }: { children?: ReactNode }): React.ReactElement => <>{children}</>
```

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +    <Text as="h1" textStyle="h2" my="0">
I goofed on the ACs.  Originally I thought this had to render an `h1` tag for accessibility, but it turns out that you can start at any h-level (you just don't want to skip levels).  Therefore, it's probably simpler to change this to the following:

```suggestion
    <Text as="h2" my="0">
```

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderBreadcrumbRow: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
Same comment here as for the item.

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +      }
This block is probably redundant.

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +        flex-direction: row;
Could you add `align-items: center;` here?  The vertical alignment of `Header.Item`s is a bit off.

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.test.tsx
> +              <Breadcrumb.Item href="/" active>
Could you change this to the following?  The last item will typically not be a link.

```suggestion
              <Breadcrumb.Active>
```

2021-03-15 21:46 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +  padding-top: ${(p) => !p.mainColumn && '24px'};
I don't see the `mainColumn` prop being passed anywhere.  Also, the Header.Title is not vertically centered on mobile screens because of this style setting.  Instead you could change this to `:last-child` (and then override it for the non-mobile view).

2021-03-16 10:54 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +          (child: any) => child.type.displayName === 'HeaderBreadcrumbRow' && <>{child}</>
Thanks, @mikesoltow ! I wonder if you know about some useful links (tutorials, blogs, etc...) where I could take a deep dive into Typescript and React Types (In addition to the documentation)

2021-03-16 11:01 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.story.tsx
> +import * as icons from '@repay/cactus-icons'
This is very practical and saves us lines of code, thanks!

2021-03-16 11:22 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +  padding-top: ${(p) => !p.mainColumn && '24px'};
you're right, at the beginning I was using a `mainColumn` prop but I decided to remove it because I started working with `:last-child` and `:first-child`. Probably I messed this change by undoing a temporal commit (I use temporal commits during the development process to keep a track of my work before the definitive commit and pushing)  
Thanks!

2021-03-16 11:28 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderItem: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({ children }) => {
@mikesoltow That's a lot better than what I've done here. There is a problem here though when I implement your suggestion: neither the BreadcrumbRow and the Items are being rendered. 

That's weird, I will take a look to find why is this happening.

2021-03-16 11:45 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +  padding-top: ${(p) => !p.mainColumn && '24px'};
@mikesoltow I just noticed an issue there with our approach, lol. When a user creates a  `Header` 
 without any `Header.Items` the `:last-child` styles will be applied to the first main column (I'm conditionally rendering the second column if there are `Header.Item`s )

I think that maybe my first approach, the `mainColumn` prop, turns out again as a possible solution to this, let me know if you have any comment about this.

2021-03-16 11:53 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.test.tsx
> +  })
@mikesoltow I could render a complete `Header` component with all of its sub-components and take a single snapshot inside this test too. I'm not completely sure about the main differences between the snapshot tests vs screenshot tests but I think a snapshot is very useful in the development process (I execute the unit tests while I'm creating or modifying a component for paying attention to snapshot changes).

It seems I could be a little confused about snapshot and screenshot tests, let me know if so, thanks!

2021-03-16 14:27 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +          (child: any) => child.type.displayName === 'HeaderBreadcrumbRow' && <>{child}</>
I don't unfortunately.  I was playing around with this just using VSCode's IntelliSense.  I deleted the `any`s and looked at what it was complaining about.  It indicated that `child` was of type `React.ReactNode`.  I could then CMD+Click on the React types in VS code to be taken to the type definitions.  And I could see that the problem was that `React.ReactNodes` are not guaranteed to have a `displayName` on them (only some descendants of `ReactNode` have that property).  We need to make a [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) to tell TypeScript that we know the children will be an element that has a `displayName`.  Some more clicking in the type definition files led me to to the type we needed to assert on.

2021-03-16 17:11 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.test.tsx
> +  })
Good point about the development process.  If you find snapshot tests helpful during development, then we can certainly leave them in.  I typically don't develop alongside with snapshot tests, as I don't find the snapshots very readable.  I just keep checking Storybook for visual changes as I develop.  I _do_ practice TDD for behavior changes however (i.e. does the Select dropdown close when you hit ESC).

That being said, that's just my method.  If it helps you to develop alongside snapshot tests, then please leave them in!

2021-03-16 17:20 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +  padding-top: ${(p) => !p.mainColumn && '24px'};
Ah, good point!  I think the `mainColumn` approach is fine.  However, you should remove the last bit of `:last-child` styles as well.  The `flex-direction: row` and `align-items: center` styles should only be applied to the non-main column (in the larger screens only).

2021-03-16 17:22 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +  padding-top: ${(p) => !p.mainColumn && '24px'};
Actually, one other comment on `align-items`: it looks like the breadcrumbs should be centered over the header title on the mobile view.  Therefore, you'll want `align-items: center` to apply to everything on mobile view, and `align-items: center` to apply to just the non-main column on the larger screens.

2021-03-16 17:24 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.test.tsx
> +  })
If you decide to not add these tests back in, then you'll need to delete the obsolete snapshots by running `yarn web test -u` to fix the build.

2021-03-16 17:32 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderItem: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({ children }) => {
I think it might be a weird TypeScript thing.  Try changing it to:

```
export const HeaderItem: FC = ({ children }) => <>{children}</>
```

2021-03-17 17:03 UTC, Dhalton approved these changes
LGTM

2021-03-17 19:36 UTC, mikesoltow approved these changes
LGTM!  Thanks for the changes

2021-03-17 20:28 UTC, merged