Cactus 550: accordion alignment
repaygithub/cactus pull request #554
Opened 2021-03-17 11:09 UTC by daniloPenaR

[CACTUS-550](https://repayonline.atlassian.net/secure/RapidBoard.jspa?rapidView=102&projectKey=CACTUS&modal=detail&selectedIssue=CACTUS-550)

Following [this workaround](https://github.com/philipwalton/flexbugs/issues/231), the problem seems to be (obviously IE11) that a `min-height` property breaks other properties like `align-items`. 

Test: 

- Open Accordion, Basic usage story on IE11 
- Make sure that the elements inside the menu are centered.
- Test it on mobile and ipad views.

2021-03-17 23:21 UTC, Dhalton approved these changes
LGTM

2021-03-18 16:40 UTC, mikesoltow requested changes

2021-03-18 16:40 UTC, mikesoltow commented on modules/cactus-web/src/Accordion/Accordion.tsx
> +  height: 24px;
This solution doesn't work if you have super-long content in the Accordion.  To test this, try using the Storybook knobs to create super-long text (see screenshot), and note that it overflows the top and bottom boundaries.  This doesn't happen in the deployed version.

Instead, I'd try a different workaround from the same thread you linked in the PR.  https://github.com/philipwalton/flexbugs/issues/231#issuecomment-362790042

This seems to work better in all cases.
![Screen Shot 2021-03-18 at 12 40 37 PM](https://user-images.githubusercontent.com/46460514/111663413-2998b180-87e7-11eb-8705-c8ac0cd77f10.png)

2021-03-18 16:43 UTC, daniloPenaR commented on modules/cactus-web/src/Accordion/Accordion.tsx
> +  height: 24px;
Doh, I didn't test it with a long string, going to look for another solution.

2021-03-19 16:54 UTC, Dhalton commented
Updates look good to me. Nice catch, Mike.

2021-03-19 19:04 UTC, mikesoltow requested changes
If you look at the updated screenshot, you can see that the IconButtons no longer line up toward the end on the With Outline story.  This is probably because of the `width: 90%;` bit that was added.  What did that fix again?

2021-03-23 17:00 UTC, mikesoltow approved these changes
LGTM!

2021-03-23 17:03 UTC, merged