CACTUS-516 :: Preview Component
repaygithub/cactus pull request #565
Opened 2021-04-08 22:56 UTC by Dhalton

Ticket: https://repayonline.atlassian.net/browse/CACTUS-516

Some Notes

- I'm not sure how we could indicate to a screen-reader that the image that has focus can be expanded. If anyone knows how we could do that, let me know.
- If you click on the REPAY logo in the preview, you'll see that it looks pretty weird with images that have transparent backgrounds. Should we maybe render a `div` with a white background around the image to help alleviate that?
- Also, this looks pretty bad on mobile. There aren't any mobile designs so we should probably circle back to this when we have those.

### Testing
1. Open the Preview "Basic Usage" story
2. Make sure you can cycle through the images using both your mouse and your keyboard.
3. Make sure you can expand an image both by clicking on it and using your keyboard.
4. Repeat steps 2 & 3 in the "From Children" story.
5. Turn on your screen reader and make sure it works with that. Only the "From Children" story will have descriptions for the images when you focus on them.

2021-04-09 17:20 UTC, mikesoltow commented
> I'm not sure how we could indicate to a screen-reader that the image that has focus can be expanded. If anyone knows how we could do that, let me know.

This could be my extreme naïveté regarding accessibility and disabilities, but what would expanding the image accomplish if you were browsing the site with a screen reader?  All the user has to interact with, regardless of size, is some alt text, right?

2021-04-09 17:21 UTC, mikesoltow commented
> Also, this looks pretty bad on mobile. There aren't any mobile designs so we should probably circle back to this when we have those.

I'm happy circling back to this later.  There's certainly no rush.

2021-04-09 18:27 UTC, Dhalton commented
> This could be my extreme naïveté regarding accessibility and disabilities, but what would expanding the image accomplish if you were browsing the site with a screen reader? All the user has to interact with, regardless of size, is some alt text, right?

Yep anyone who's visually impaired would be relying on the alt text for a description, so it's probably fine as-is.

2021-04-09 19:03 UTC, mikesoltow reviewed
Looks pretty good to me.  All my comments are just some suggestions and are pretty minor.

2021-04-09 19:05 UTC, mikesoltow commented
> If you click on the REPAY logo in the preview, you'll see that it looks pretty weird with images that have transparent backgrounds. Should we maybe render a div with a white background around the image to help alleviate that?

Oh...I forgot to address this.  I think that's not a bad idea if it's easy to add in there.

2021-04-09 19:07 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.test.tsx
> +  })
Nah, I just left it in there to keep these tests the same as the rest, but I'm happy to remove it. I think we should remove all of the snapshots now that we have some confidence in the visual tests, but that's a task for another day.

2021-04-09 19:07 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.test.tsx
> +      expect(getByAltText('Cute kitten number 1')).toBeInTheDocument()
Good call!

2021-04-09 19:08 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.test.tsx
> +      expect(getAllByAltText('Cute kitten number 1')[1]).toBeInTheDocument()
🤦  Should've thought of that. Yes, thanks for pointing that out!

2021-04-09 19:10 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +          selectedImage !== null &&
You know what, I think you're right. It can probably be removed since the ref would be null if there's no expanded image, anyway. I'll get rid of it.

2021-04-09 19:10 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +    const [selectedImage, setSelectedImage] = React.useState<number | null>(null)
Good thinking 👍

2021-04-09 19:12 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +const PreviewBox = styled.div<{ $justify: 'space-between' | 'center' }>`
I'll try it out, thanks for the suggestion

2021-04-09 19:50 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +    }
After looking into this a bit more, I think we should leave the click handler there so that it works with the keyboard input too.

2021-04-09 19:53 UTC, mikesoltow commented on modules/cactus-web/src/Preview/Preview.tsx
> +    }
Does removing it break the keyboard interaction?  I thought it had still worked when I removed it, but maybe I messed up somehow.  In any case, it doesn't really hurt to leave this in.

2021-04-09 19:57 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +          selectedImage !== null &&
Turns out this condition is necessary. If I remove it, when I click on an image to expand it, the other two conditions yield a truthy value and immediately set the selected image back to `null`.

2021-04-09 20:01 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +          selectedImage !== null &&
I also tried checking `selectedImageRef !== null` instead of what I have here, but apparently at the time that the function is called, it is _not_ null, so that doesn't work either.

2021-04-09 20:03 UTC, mikesoltow commented on modules/cactus-web/src/Preview/Preview.tsx
> +          selectedImage !== null &&
Ah okay.  No biggie.  I didn't notice any performance issues or anything, so leaving it as-is doesn't hurt anything.

2021-04-12 18:36 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +    }
On Friday, I thought it was breaking the keyboard interactions, but I think I just wasn't passing `keyDownAsClick` to the X button correctly. I removed it and it looks like it does still work. 👍

2021-04-12 19:00 UTC, mikesoltow requested changes
Change look pretty good, but something got messed up on IE (see screenshot), and the kitten looks really sad about it.  Also, I don't know if we want to implement some sort of scrolling function (in another ticket) for images that are too tall when expanded?

![Screen Shot 2021-04-12 at 2 57 52 PM](https://user-images.githubusercontent.com/46460514/114446881-b85add00-9b9f-11eb-816d-cfb9829c90ff.png)

2021-04-12 19:00 UTC, mikesoltow commented on modules/cactus-web/src/Preview/Preview.tsx
> +      if (imageSelected !== null) {
```suggestion
      if (imageSelected) {
```

2021-04-12 22:15 UTC, Dhalton commented
> Change look pretty good, but something got messed up on IE (see screenshot), and the kitten looks really sad about it. Also, I don't know if we want to implement some sort of scrolling function (in another ticket) for images that are too tall when expanded?

Thanks for pointing this out. It slipped by me because my session in browserstack wasn't displaying storybook's knobs section at the bottom, so it had enough vertical space. I went ahead and added a wrapper that allows a user to scroll if it overflows. I would've waited to do it in another ticket, like you suggested, but that was part of the problem in IE so right now seemed like a good time to handle it. Let me know if that works for you!

2021-04-13 21:05 UTC, mikesoltow reviewed
This looks great.  Just one suggestion, otherwise I'm good.

2021-04-14 16:40 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +            <Flex height="100%" flexDirection="column" alignItems="center">
Whoops yeah that was definitely an oversight on my part. I pushed up a fix for it 👍

2021-04-15 16:03 UTC, mikesoltow approved these changes
LGTM 🐱

2021-04-15 21:45 UTC, wilysword reviewed
I think pretty much all my comments are code style comments, but I do have a question about the expanded view: shouldn't that open the image at full size? I noticed when I opened the REPAY logo while I had the browser maximized it was larger than when the window was smaller; but if the expanded view is still not the full size image, what purpose does it serve?

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +    Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'onError' | 'onFocus' | 'onBlur'> {
You only need to omit things if you're defining them yourself. I don't think there's any reason to do so here.

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +  close?: string
Why is one of these required? Should be all or none, I think.

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +    }, [imageSelected])
Out of curiosity, why have two effects with the exact same criteria?

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +    const imagesFromChildren = images.length === 0 && !!children
You use this variable in quite a few places, but I think it might make more sense to just get a single source of truth for the children:
```
const imgComponents = images.length ? images.map((src) => (<img src={images[currentIndex]} />) : React.Children.toArray(children)
```
Or you can just do that with the current index and the array length, if it concerns you to be creating components you won't render.

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +            onKeyDown={keyDownAsClick}
Add `onKeyUp={preventAction}` wherever you use this. It's not required, strictly speaking, but if you use `keyDownAsClick` on `<button>` elements, activating the button using `space` instead of `enter` results in _two_ click events.

2021-04-15 21:45 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +            'data-selected': 'false',
I don't see the purpose of this attribute. As far as I can tell you're only using it for styling, but it looks like it's only set to `true` inside the `ImageBackground` element, so you could just as easily use that as the differentiator.
```
${ImageBackground} img {
  styles: galore;
}
```

2021-04-15 21:47 UTC, wilysword commented
Also, maybe a nice-to-have: if pressing Escape when in the expanded view closes it.

2021-04-15 21:51 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +  width: 50%;
Should this be `max-width: 80%`?

2021-04-15 23:17 UTC, Dhalton commented
> I noticed when I opened the REPAY logo while I had the browser maximized it was larger than when the window was smaller; but if the expanded view is still not the full size image, what purpose does it serve?

My understanding of the purpose of this feature was to enlarge the image so that you can see it better. Right now, it has a hard width set at 50% of your viewport width, which I felt would probably be a reasonable size to get a good view of the image. Now that I think about it, though, I guess if you had a very large image, that constraint could technically make the image appear to be smaller than it really is. I can free up the width restrictions on the images when you blow them up, but when I was working on this it always felt strange to click on an image and then end up seeing a _smaller_ image than the one in the preview.

2021-04-15 23:19 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.mdx
> +    <img src="http://placekitten.com/400/450" alt="Cute kitten number 1" />
You mean the placekitten website? My guess is that it exists precisely for use-cases like this, when you need some dummy images with specific sizes. In any case, I'm glad it does. 😝

2021-04-15 23:20 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +  close?: string
Yep, typo. Thanks for pointing this out.

2021-04-15 23:21 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +    }, [imageSelected])
Looks like an oversight on my part. I'll consolidate them into one.

2021-04-15 23:24 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +            'data-selected': 'false',
Yeah, the thing is I also need to make sure the styles that are being applied to the images inside the preview are not also being applied to the image that's expanded. I can do what you're suggesting and just overwrite the styles from the preview images, though.

2021-04-15 23:26 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +  width: 50%;
There isn't anything mentioned in the style guide about how wide the expanded images should be, which is what this is a wrapper for. The style guide does mention that the images in the preview should have a max width of 80% of the preview width, but that styling is done elsewhere.

2021-04-15 23:29 UTC, wilysword commented on modules/cactus-web/src/Preview/Preview.tsx
> +  width: 50%;
I was thinking of the AC that says "The max width of the image _in expanded view_ is 80% of the viewport width" (emphasis added).

2021-04-16 17:46 UTC, Dhalton commented on modules/cactus-web/src/Preview/Preview.tsx
> +  width: 50%;
Ah, yeah I must've missed that. Whoops!

2021-04-16 18:40 UTC, Dhalton commented
@wilysword Alright I think I addressed all of your comments. @mikesoltow You may want to re-review this too.

2021-04-16 20:56 UTC, wilysword approved these changes

2021-04-19 16:09 UTC, merged