Cactus 569 :: header improvements
repaygithub/cactus pull request #566
Opened 2021-04-09 20:48 UTC by daniloPenaR

- [x] _Horizontal padding is added to the mobile version of the header_: 16px of horizontal padding
- [x] _The Header.Item component should have horizontal spacing on desktop mode and vertical spacing on mobile mode _ : 8px of Horizontal and vertical margin added
- [x]  _The Header.Item component should render a div_ : the `Header` item now returns a `<div>{children}</div>` and passing `{...props}`

- [x] _All props passed into the `Header.Title `component should be passed into the rendered_ : Now the props of the `Header.Title` are passed directly to the Text component via `{...props}`

2021-04-12 17:06 UTC, mikesoltow requested changes
This looks mostly great.  In fact, all of the comments in the code are just minor suggestions: you can take them or leave them.

The only reason I've requested changes is that long headers seem to overflow the page on Firefox's mobile view.  The only thing I was able to do to fix it was to add a bunch of `max-width: 100%` lines to the `div` and `h2` inside `Header.Title`, but I feel like I'm missing something more fundamental..

2021-04-12 17:24 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +    margin-top: ${(p) => !p.mainColumn && '8px'};
Here I am using the `:not(:first-child)` to prevent that the first element of the possible array of `HeaderItems` will not take the `margin-top` property. Otherwise, an extra space of 8px will be added between the `mainColumn` and the items column

<img width="571" alt="Screen Shot 2021-04-12 at 12 20 26 PM" src="https://user-images.githubusercontent.com/77983162/114435276-9bb3aa80-9b89-11eb-91bd-485a9e8995f6.png">

2021-04-12 17:27 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +    margin-top: ${(p) => !p.mainColumn && '8px'};
if I put something like this 
```
 > div {
    margin-top: ${(p) => !p.mainColumn && '8px'};
  }
```
An extra space will be added on the top of the first element
<img width="407" alt="Screen Shot 2021-04-12 at 12 26 18 PM" src="https://user-images.githubusercontent.com/77983162/114435925-5fcd1500-9b8a-11eb-911f-52076fe4f514.png">

2021-04-12 18:42 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +    margin-top: ${(p) => !p.mainColumn && '8px'};
D'oh!  You are right!  My mind was not at the right level in the hierarchy...I wash thinking that the "first child" was the main column.

2021-04-12 19:11 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +    margin-top: ${(p) => !p.mainColumn && '8px'};
So I think I could skip the two comments below if you agree :)

2021-04-12 19:12 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +    margin-top: ${(p) => !p.mainColumn && '8px'};
Fine by me!

2021-04-13 17:31 UTC, mikesoltow reviewed
Changes look good in everything except IE.  For some reason, the header text is overflowing when it's too long (see screenshot).
<img width="940" alt="Screen Shot 2021-04-13 at 1 30 11 PM" src="https://user-images.githubusercontent.com/46460514/114595541-7e9bdc00-9c5c-11eb-82ff-441a8d97faa1.png">

2021-04-13 17:31 UTC, daniloPenaR commented
> Changes look good in everything except IE. For some reason, the header text is overflowing when it's too long (see screenshot).
> <img alt="Screen Shot 2021-04-13 at 1 30 11 PM" width="940" src="https://user-images.githubusercontent.com/46460514/114595541-7e9bdc00-9c5c-11eb-82ff-441a8d97faa1.png">

Gotcha, going to solve.

2021-04-15 16:22 UTC, mikesoltow reviewed
There's something something weird going on in the mobile view of IE11, but it's _probably_ not worth a fix (unless it takes 5 mins), as I don't think anyone uses IE11 on tiny screens.

Other than that, there's just my one comment.

2021-04-15 16:22 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +      }
I think we want to flip the "not first child" selectors.  As it stands, the first child is getting a top margin while the others aren't (see screenshot where the first button is lower than the next two items).  Also, all of the buttons are getting a left margin.  Not sure if that's intended or if you wanted the first item to have no left margin.

```suggestion
      > div {
        margin-top: ${!p.mainColumn && '0px'};
      }
      > div:not(:first-child) {
        margin-left: ${!p.mainColumn ? '8px' : '0px'};
      }
```

![Screen Shot 2021-04-15 at 12 17 35 PM](https://user-images.githubusercontent.com/46460514/114903459-d5ccb880-9de4-11eb-85c8-1f7a06492300.png)

2021-04-15 17:25 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +      }
@mikesoltow Well, at the first time I omit the left-margin in the first item just to prevent aggregating too much space between the title/mainColumn and the first item

2021-04-15 23:04 UTC, Dhalton commented
I'm seeing some weird-ness in the iPad view...see screenshot below. It looks like we need to provide more space for the title/breadcrumbs. I think it'd make more sense for the header items to wrap onto the next line than for the title/breadcrumbs to do that. Or maybe if there are several header items like that they should just be rendered below the title. I'm having trouble locating the designs for the header, so I'm not sure what the designers recommend at that screen size, but I think either one of those suggestions would at least help clean it up.

![Screen Shot 2021-04-15 at 3 53 11 PM](https://user-images.githubusercontent.com/39279144/114948598-2e5f7e00-9e04-11eb-8a16-b73c157964d4.png)

2021-04-19 17:33 UTC, daniloPenaR commented
there's the weirdness in the  IE11's Mobile view and I tried it to solve by adding many CSS properties as `flex` or `min-width` but I can't figure out what is happening... Maybe I am missing any petite detail or something

2021-04-19 20:43 UTC, Dhalton commented on modules/cactus-web/src/Header/Header.story.tsx
> +        <Text>You are configuring Merchant directory from OWE Demo Merchant</Text>
Why remove all of the other things that were being rendered here? This was the story that started the conversation about rendering the header items in a separate column...I can't check to see how it looks with the changes you made if the extra items aren't here anymore.

2021-04-20 15:31 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.story.tsx
> +        <Text>You are configuring Merchant directory from OWE Demo Merchant</Text>
@Dhalton  Sorry! As we were discussing on Friday in a thread via `ui-team`, we don't have many use cases for three long items in the right column, and on that day we were testing how a long text like that does look in different screen sizes. However, I set the small view to aligning the items in the right part and in a single column. 

I have restored that use case, so you can take a look again 👍

2021-04-20 18:12 UTC, Dhalton commented on modules/cactus-web/src/Header/Header.tsx
> +      flex: 0 1 auto;
```suggestion
      flex: 0 1 auto; 
      > div:not(:first-child) {
        margin-top: 0px;
      }
```

Other than that I'm ready to approve this

2021-04-20 22:39 UTC, Dhalton approved these changes
I think you've addressed all of my concerns. As far as the weird overflow thing in IE11 on mobile goes, obviously it'd be nice to fix it, but at the end of the day I don't even think it's _possible_ to use IE on a mobile device, so I'm not too worried about it.

2021-04-21 14:49 UTC, mikesoltow reviewed
Sorry...I found a couple more things!  The overall changes do look good though.

2021-04-21 14:49 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +    > h2 {
This selector won't work if the use does something like `<Header.Title as="h3">`.  Also, if the Breadcrumbs have many items, it's possible for them to overflow on IE11 as well.  I think we can just change this selector to `> *` unless you can think of a reason why that wouldn't be good.

2021-04-21 14:49 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderTitle: FC = ({ children, ...props }) => {
Sorry for not realizing this sooner, but these `props` have a type of `{}` because you haven't defined a props interface for this component.  I think you can change `FC` to `FC<React.ComponentProps<typeof Text>>`, as that should give the same props interface that `Text` has (which is what we want, since we're rendering a `Text` component).

2021-04-21 14:49 UTC, mikesoltow commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderItem: FC = (props) => <div {...props} />
Similar to my previous comment, we'll want to add a type for `props` here.  For this one, you could use:

```typescript
FC<
  React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>
>
```

(I got this by hovering over a `div` element in VSCode and copying the type signature for the props.)

2021-04-21 15:58 UTC, daniloPenaR commented on modules/cactus-web/src/Header/Header.tsx
> +export const HeaderTitle: FC = ({ children, ...props }) => {
Nice catch, I was interpreting this `...props` in the wrong way. Definitively need to practice and learn too much about Typescript's type declarations.

2021-04-22 15:40 UTC, daniloPenaR commented
@mikesoltow I'm currently running the `test:docker-update` so I hope the last changes will be here in the next hour. I cannot get logged into any browserstack account cause I'm having problems with the LastPass login too (they said they'll send me an email but nothing has come)...

2021-04-23 13:44 UTC, mikesoltow approved these changes
Looks good...thanks, Danilo!

2021-04-23 14:15 UTC, merged