CACTUS-582 :: Dark Variants
repaygithub/cactus pull request #577
Opened 2021-04-27 14:29 UTC by daniloPenaR

[CACTUS-582](https://repayonline.atlassian.net/browse/CACTUS-582)

2021-04-27 16:06 UTC, mikesoltow requested changes
Just a few comments, but otherwise it looks good.

I'm wondering if all the random updated stories have to do with the new `node` docker image.  That's the only thing that would make sense (plus, it seems like only "default viewport" screenshots updated, so maybe the new image's "default viewport" has changed 🤷 ).

2021-04-27 16:06 UTC, mikesoltow commented on modules/cactus-web/src/IconButton/IconButton.tsx
> +    }
Setting the hover to `darkestContrast` doesn't lead to much change on hover, as the colors are too close together.  How would you feel about using `callToAction`?   That's currently what we use for `Breadcrumb.Link`.

2021-04-27 16:06 UTC, mikesoltow commented on modules/cactus-web/src/IconButton/IconButton.story.tsx
> +    <StyleProvider theme={cactusTheme} global>
Can you remove the `StyleProvider` from here?  This overrides the ability to use the Cactus Theme tab to play with the theme colors on this story.  All stories are already wrapped in a provider.

2021-04-27 16:57 UTC, daniloPenaR commented on modules/cactus-web/src/IconButton/IconButton.story.tsx
> +    <StyleProvider theme={cactusTheme} global>
Just have one question, if I drop the StyleProvider here, the ScreenSizeProvider will keep useful? I read on the docs that the screenSizeProvider must be nested inside the StyleProvider to show the size correctly.

> The possible sizes are directly from the media queries object ("small", "medium", "large", "extraLarge"), with the addition of "tiny" when none of the media queries match. Because it uses `theme.mediaQueries`, it should be nested inside a `StyleProvider`; otherwise it will always give the default size of "large".

And when I was implementing it, the ScreenSizeProvider was throwing me always the same size

2021-04-28 16:46 UTC, wilysword approved these changes

2021-04-28 17:34 UTC, Dhalton commented
LGTM just waiting for the build to finish before I approve

2021-04-28 18:05 UTC, Dhalton approved these changes

2021-04-28 18:06 UTC, merged