CACTUS-598 :: Breadcrumbs Ellipsis
repaygithub/cactus pull request #582
Opened 2021-04-30 23:50 UTC by daniloPenaR

[CACTUS-598](https://repayonline.atlassian.net/browse/CACTUS-598)

I made many tests just to make sure the ellipsis is being activated when the screen size requires it. But for some reason, I distrust the object returned by the `getBoundingClientRect()` function, please let me know if you found something stranger...

2021-05-03 22:48 UTC, Dhalton reviewed
Something is definitely off, but I haven't quite been able to pinpoint the source of the problem yet. It seems like there's a certain screen size, about at iPad view width, where the component isn't switching to the ellipsis version when it should be. See screenshot:

![image](https://user-images.githubusercontent.com/39279144/116942568-add3b680-ac26-11eb-97d0-3829a4adc63a.png)

Note that I added an extra link to the "Huge list of breadcrumbs" story to cause this to happen.

It looks like, for some reason, the value of `pivotWidth` is less than what it is in reality. Again, I haven't been able to figure out why or how to fix it yet, though. I'll keep playing around with it tomorrow, but wanted to point it out so you're aware.

2021-05-03 22:48 UTC, Dhalton commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx
> +      (pivotWidth && parentNavContainerWidth && pivotWidth > parentNavContainerWidth) ||
This condition should probably be checking `pivotWidth >= parentNavContainerWidth` instead of just `>`.

2021-05-03 22:48 UTC, Dhalton commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx
> +  <Flex>
Why wrap these in a `Flex`? All that's doing for me is preventing the component from realizing that it has enough space when you size back up from something like iPad view to desktop view.

2021-05-03 22:50 UTC, Dhalton commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx
> +  <Flex>
If you want to keep the flex I'd say at least give it a fixed width, but honestly I don't know why it's necessary at all.

2021-05-04 16:57 UTC, daniloPenaR commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx
> +  <Flex>
You're right, wrapped the Breadcrumbs into `Flex` from my first commit when I was trying to solve these issues in a different way, and I forgot to get rid of those wrappers with the newer approach. I will not preserve those wrappers, thanks for point it out.

2021-05-05 17:58 UTC, Dhalton requested changes
I'm almost ready to approve. I think my only concerns are with the stories.

2021-05-05 17:58 UTC, Dhalton commented on modules/cactus-web/src/Layout/Layout.story.tsx
> +              <Breadcrumb.Item>
This should be
```
<Breadcrumb.Item as={Link} to="/">
  Make a Payment
</Breadcrumb.Item>
```
otherwise you get console errors regarding having an `<a />` tag as a child of another `<a />` tag.

2021-05-05 17:58 UTC, Dhalton commented on modules/cactus-web/src/Header/Header.story.tsx
> +            <Breadcrumb.Item href="/">{`label ${i}`}</Breadcrumb.Item>
Need to set a `key` prop on these. Getting console errors about it.

2021-05-05 17:58 UTC, Dhalton commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx
> +    <Breadcrumb.Item>
This should be
```
<Breadcrumb.Item as={Link} to="/">
  Make a Payment
</Breadcrumb.Item>
```
otherwise you get console errors regarding having an `<a />` tag as a child of another `<a />` tag.

2021-05-05 17:58 UTC, Dhalton commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx
> +      <Breadcrumb.Item key={i} href="/">{`label ${i}`}</Breadcrumb.Item>
Need to set a `key` prop on these. Getting console errors about it.

2021-05-05 21:09 UTC, wilysword reviewed
Just a couple of comments about code organization, plus what Dhalton said about story console warnings. Looks good, functionally.

2021-05-05 21:09 UTC, wilysword commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx
> +    }
Couple of changes I recommend in this function:
```suggestion
    const parentWidth = Math.ceil(mainNavContainer.current?.parentElement?.getBoundingClientRect().width)
    const pivotWidth = Math.ceil(pivotBreadcrumb.current?.getBoundingClientRect().width)
    const ellipsisVersion = pivotWidth >= parentWidth || (isTiny && childrenCount > 2)
    setEllipsisVersion(ellipsisVersion)
```
The `Math.ceil` is to (hopefully) avoid rounding/truncation errors. Then instead of setting the state twice, I think you only really need to set it once.

2021-05-05 21:09 UTC, wilysword commented on modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx
> +  }, [checkEllipsisVersion])
It would be better to implement the `checkEllipsisVersion` function in here, since this is where it's being used:
```suggestion
  React.useLayoutEffect(() => {
    const checkEllipsisVersion = () => {
      // ...etc
    }
    checkEllipsisVersion()
    window.addEventListener('resize', checkEllipsisVersion)
    return () => {
      window.removeEventListener('resize', checkEllipsisVersion)
    }
  }, [childrenCount, isTiny])
```

2021-05-06 17:36 UTC, wilysword approved these changes

2021-05-06 18:16 UTC, Dhalton approved these changes

2021-05-06 18:42 UTC, merged