CACTUS 608:: Switch ConfirmModal Buttons
repaygithub/cactus pull request #588
Opened 2021-05-11 21:12 UTC by daniloPenaR

[CACTUS-608](https://repayonline.atlassian.net/browse/CACTUS-608)

2021-05-11 22:21 UTC, Dhalton requested changes
Just the comment about the margin and then I'm good to approve.

2021-05-11 22:21 UTC, Dhalton commented on modules/cactus-web/src/ConfirmModal/ConfirmModal.tsx
> +        <TextButton onClick={onClose}>{cancelButtonText}</TextButton>
We still need to maintain the spacing between the buttons. Gotta remove the `marginRight="24px"` from `Button` below this line and add it onto this `TextButton` instead. While you're at it you might as well just use `mr={5}`, which does the same thing but has the added benefit of staying in-line with the design system if the spaces we have defined were to ever change.

2021-05-12 16:28 UTC, Dhalton approved these changes
LGTM thanks for making those changes

2021-05-12 16:48 UTC, wilysword approved these changes

2021-05-12 21:42 UTC, merged