Cactus 604 :: usermenuitem
repaygithub/cactus pull request #597
Opened 2021-05-26 15:27 UTC by daniloPenaR

[CACTUS-604](https://repayonline.atlassian.net/browse/CACTUS-604)

- got rid of all the Reach elements in the Brandbar. 
- Implemented the `usePopup` hook to replace the Reach library
- Changed the UserMenuItem component for a similar one from MenuBar
- Now, the UserMenuItem component allows the `as` prop and it can be used as a `Link`
- Finally, breaking change: `onSelect` prop is no longer available for the UserMenuItem, use `onClick` instead

Thanks to Glen for all the support.

2021-05-26 17:28 UTC, wilysword requested changes

2021-05-26 17:28 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
>      z-index: 110;
Should move this z-index style up to the `MenuList` styles instead of just the menuitem styles.

2021-05-26 17:28 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    &:hover {
Focus and hover styles need to be different. For hover, try this instead:
```
&:hover {
  color: ${(p) => p.theme.colors.callToAction};
}
```

2021-05-26 17:28 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +const positionPopup = (menu: HTMLElement, menuButton: HTMLElement | null) => {
This position function is something I whipped up for the POC, but it's too naive for the final product: it doesn't handle scrolling or menu items that are wider than the button. This one should be a bit more up to the task (though you may still need to make modifications): https://github.com/repaygithub/cactus/commit/46d75df290e05ef6d10df5afa8e9a768d9cdd2a8

2021-05-27 17:16 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +const positionPopup = (menu: HTMLElement, menuButton: HTMLElement | null) => {
@wilysword  So here you are referring to the cases we have a huge menu list wider than the viewport height?

2021-05-27 17:36 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  id = 'user-menu',
I guessed `id` is optional and we are passing it into the options object of the usePopup it was pretty much convenient to have a default. But I'm going to remove it if you think it's not necessary.

2021-05-27 17:43 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +const positionPopup = (menu: HTMLElement, menuButton: HTMLElement | null) => {
I don't think so, though I don't quite understand your question. I'm referring to two scenarios, mainly:
1. In the BrandBar -> Basic Usage story, there's a knob called "Action one". Enter some long text there, and see how the menu behaves.
2. In the Layout -> Basic Usage story, try opening the user menu and then scrolling down the page.

2021-05-27 17:44 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  id = 'user-menu',
`usePopup` will generate a random ID if none is provided, so you don't need the hard-coded default.

2021-05-27 19:56 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +const positionPopup = (menu: HTMLElement, menuButton: HTMLElement | null) => {
Gotcha, Thanks, well I am currently testing those new changes in order to find anything in those cases that requires any other modification.

2021-05-28 17:52 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    &:hover {
Still didn't fix this one.

2021-05-28 17:56 UTC, wilysword reviewed
Where did those `user-menu-wider-list` snapshots come from? There doesn't appear to be an associated story, so you should probably delete them. Aside from that and the hover styles issue, though, I think this is looking good.

2021-06-07 20:43 UTC, mikesoltow requested changes
None of my comments in the code are blockers, but I marked this as "Request Changes" because of the following issues:

* If you click to open the menu, you can then use the arrows to navigate
* In Safari, a weird outline appears when you click to open the menu.  You need to style the `div` that takes `wrapperProps` with `outline: none`.
* The `:visited` style is different in the mobile menu.  I don't think it should change, as it looks weird to have one menu item styled differently than the others.
* If you change a menu item to be something really long, it works fine on desktop/tablet but overflows on mobile.
* You should be able to hide a menu using ESC, but that doesn't seem to work.

2021-06-08 23:36 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +import { SidebarMenu as ActionMenuPopup } from '../MenuBar/MenuBar'
Did you mean, preserving the same import name `SidebarMenu`

2021-06-08 23:43 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
>      },
You're right, Glen recommended to just put into the `popupProps`

2021-06-08 23:46 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  )
But here in Brandbar we need to add the `tabIndex` property to enable the navigation with the arrow keys.

2021-06-09 16:25 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.test.tsx
> -
But why did this change?  Before we needed to use the arrow twice?

2021-06-09 16:26 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  )
That happens in `MenuBar.tsx` as well, it just happens in the `MneuButton` component itself.  See https://github.com/repaygithub/cactus/blob/master/modules/cactus-web/src/MenuBar/MenuBar.tsx#L555

2021-06-09 16:28 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +import { SidebarMenu as ActionMenuPopup } from '../MenuBar/MenuBar'
No, I was thinking that, if we created a helper file for the shared menu item stuff, then we put SidebarMenu in that file as well, since it's shared.  It makes more sense to me to have two components import it from a helper file than to have one component import it from another component's file...when those two components don't have a hierarchical relationship or anything like that.

It's not strictly necessary, but just a suggestion for organization.

2021-06-09 16:52 UTC, mikesoltow requested changes
Looks better!  Just a few more items to address.

Also, it looks like the `:visited` style still hasn't been updated:
>The :visited style is different in the mobile menu. I don't think it should change, as it looks weird to have one menu item styled differently than the others.

2021-06-09 16:52 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.story.tsx
> +    await page.click(`[id="user-menu-button"]`)
What does this change do?

2021-06-09 16:52 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    buttonId: 'user-menu-button',
What does adding a `buttonId` do?

2021-06-09 16:52 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  }
This doesn't fix the problem, as the focus and hover styles need to be different.  To see an example, open up a MenuBar dropdown and scroll to an item with the arrow keys.  Then hover on the item above it with your mouse.  Notice how the two have different styles.

2021-06-09 16:52 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +  word-break: break-word;
Remember that this doesn't work in IE11.  There are a couple of other places in this file that should be corrected as well.

```suggestion
  word-wrap: break-word;
  overflow-wrap: break-word;
```

2021-06-10 15:04 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.story.tsx
> +    await page.click(`[id="user-menu-button"]`)
Oh sorry, I was performing some changes and playing around with the screenshot's parameters and when I wrote that again I put them on that way, going to undo that now.

2021-06-10 15:09 UTC, daniloPenaR commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    buttonId: 'user-menu-button',
This `buttonId` adds an `id` property for the element that contains the `buttonProps`. If you don't define a name for that id, the Hook will add a random one, and this line
```javascript
await page.click('[id="user-menu-button"]')
```
in the story will throw us an error.

2021-06-10 17:06 UTC, wilysword commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    buttonId: 'user-menu-button',
You should still find a different selector; maybe add a className, if it doesn't already have a unique one (from `styled`)? The reason we don't want to hard-code IDs is because they're supposed to be unique. Although this specific component shouldn't appear more than once on the page, what if the dev wanted to use that ID somewhere in the page content?

2021-06-11 17:16 UTC, wilysword reviewed
Styles on larger screen sizes look better, but the `:hover`/`:focus`/`:visited` styles on tiny/mobile screens are still off.

2021-06-14 16:35 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +    buttonId: 'user-menu-button',
Ah, good catch Glen.  I agree.

2021-06-16 12:00 UTC, daniloPenaR commented
@mikesoltow @wilysword What do you guys think about using `'[role="button"]'` as a selector? My guess is that using className is not a good idea, because we would need to use the entire class, isn't it? just like `class="sc-gGiJkG hvvMSH user-menu-button"`

2021-06-16 16:45 UTC, wilysword commented
A classname selector is like `.sc-gGiJkG`, and it can be used with any one of the classes (although you have to know the class, of course, so the only way to use auto-generated styled-components classes is if you have the component itself). You don't have to use that selector, though, you can use any selector as long as the first element it finds is the button you want to click.

2021-06-18 13:12 UTC, daniloPenaR commented
@wilysword So is it fine if I preserve that `role` selector?

2021-06-18 16:47 UTC, wilysword commented
As long as it works, I'm fine with it.

2021-06-18 18:09 UTC, mikesoltow reviewed
Just one more comment!

2021-06-18 19:11 UTC, daniloPenaR commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +export const MenuButton = styled.span.attrs({ tabIndex: -1 as number, role: 'menuitem' as string })`
Yeah, I'm fine with that, going to perform those changes immediately.

2021-06-18 21:41 UTC, luisniebla commented on modules/cactus-web/src/MenuItem/MenuItem.tsx
> +    <li role="none">
role=none? Why?

2021-06-18 23:21 UTC, wilysword commented on modules/cactus-web/src/MenuItem/MenuItem.tsx
> +    <li role="none">
So that screen readers ignore it.

2021-06-21 17:00 UTC, wilysword approved these changes

2021-06-21 17:08 UTC, luisniebla approved these changes

2021-06-21 20:10 UTC, mikesoltow reviewed
It's looking great, but I still see a different `:visited` style on mobile screens.  Is that just me?  (I have this branch rebased off my dependencies branch because of some issues I'm having)

2021-06-21 20:12 UTC, mikesoltow reviewed
Also, one more thing I noticed: the regular MenuBar no longer is displaying the underline on the nested menu items in tablet mode when you hover over them.

2021-06-21 20:28 UTC, wilysword commented
I figured out the `:visited` style is actually because in the story it uses `as={Link}` instead of `as="a"`. The `Link` styles are interfering with the menubutton styles.

2021-06-22 18:00 UTC, stevemom-repay reviewed
It doesn't look like there were much of any test changes short of changing from `onSelect` to `onClick`. It seems like we could be adding some additional tests to cover some of these other changes.

2021-06-23 12:07 UTC, daniloPenaR commented
> It's looking great, but I still see a different `:visited` style on mobile screens. Is that just me? (I have this branch rebased off my dependencies branch because of some issues I'm having)

@mikesoltow This is how it looks at this moment (with a hover on the Link)
<img width="243" alt="Screen Shot 2021-06-23 at 7 02 04 AM" src="https://user-images.githubusercontent.com/77983162/123093405-4568b080-d3f1-11eb-9f53-e740a45aab76.png">
<img width="476" alt="Screen Shot 2021-06-23 at 7 02 29 AM" src="https://user-images.githubusercontent.com/77983162/123093414-47cb0a80-d3f1-11eb-9c1f-f1cb7f7c77b3.png">


And this is how I've modified the default styles of the `:visited` `Link` to inherit the color property
<img width="412" alt="Screen Shot 2021-06-23 at 7 05 58 AM" src="https://user-images.githubusercontent.com/77983162/123093577-7943d600-d3f1-11eb-8fb5-2d9e7db0b8c8.png">

Do you want to be inherited, or maybe you prefer both mobile and larger screens to show the visited Link with a different color?

2021-06-23 12:09 UTC, daniloPenaR commented
> It doesn't look like there were much of any test changes short of changing from `onSelect` to `onClick`. It seems like we could be adding some additional tests to cover some of these other changes.

@stevemom-repay  Maybe I could mock the `onChange` and create some tests, I've learned new stuff about that with my current ticket lol, @mikesoltow what do you think?

2021-06-23 14:59 UTC, mikesoltow commented
> I figured out the `:visited` style is actually because in the story it uses `as={Link}` instead of `as="a"`. The `Link` styles are interfering with the menubutton styles.

Ah, you are right.  The same thing will happen on the regular menu bar, so this is not a new problem.

@daniloPenaR for this PR, I'd take out your recent commit (I'm sorry!).  We can deal with this in a separate ticket if we wish (by adding some contextual style to `Link` for when it's wrapped in our new MenuBarItem component)...or just direct users to use `as="a"` instead.

2021-06-23 18:32 UTC, daniloPenaR commented
@mikesoltow Gotcha, going to undo those changes and to solve de `MenuBar` `border-bottom` issue.

2021-06-28 16:31 UTC, mikesoltow reviewed
Just one more thing!  I thoroughly tested the rest in all browsers, and it looks good.

Regarding @stevemom-repay 's testing suggestion, I think that's a good point.  There don't appear to be a ton of behavior tests for this file, and I think it could also benefit from some more screenshot tests of cases where the menu is open and an item is selected or hovered.

That being said, this ticket has been open for quite a while.  My inclination is just to push it through and then backfill some of the tests in a tech debt ticket.  @stevemom-repay are you okay with that?  Feel free to push back if not, as this is your wheelhouse.

2021-06-28 16:31 UTC, mikesoltow commented on modules/cactus-web/src/BrandBar/BrandBar.tsx
> +      background-color: ${(p) => p.theme.colors.lightContrast};
Sorry for not catching this before, but you'll want to remove this background color on focus if you want to match the MenuBar styles.

2021-06-28 17:03 UTC, stevemom-repay commented
> Just one more thing! I thoroughly tested the rest in all browsers, and it looks good.
> 
> Regarding @stevemom-repay 's testing suggestion, I think that's a good point. There don't appear to be a ton of behavior tests for this file, and I think it could also benefit from some more screenshot tests of cases where the menu is open and an item is selected or hovered.
> 
> That being said, this ticket has been open for quite a while. My inclination is just to push it through and then backfill some of the tests in a tech debt ticket. @stevemom-repay are you okay with that? Feel free to push back if not, as this is your wheelhouse.

I think backfilling with tests at this point is fine.

2021-06-30 19:00 UTC, mikesoltow approved these changes
Thanks!  LGTM 🎉

2021-06-30 21:23 UTC, merged