CACTUS-657 Footer Redesign
repaygithub/cactus pull request #634
Opened 2021-07-26 20:26 UTC by wilysword

https://repayonline.atlassian.net/browse/CACTUS-657

First commit is kind of unrelated (read commit message for more info), but I wanted it so that people could restyle the footer easily, if they wanted, by doing something like this:
```
const NewFooter = styled(Footer)`
  .footer-logo {
    background-color: chartreuse;
  }
```
That's also why I switched to the `.attrs({ as })` styling strategy. (It's a pain that I keep learning new things and changing my mind about what the "best" way is...)

For the most part I strictly followed the style guide here. The only sort-of exception is the placement of the text. The style guide specifies a dynamic gap between the logo and text, but doesn't indicate how that should be accomplished. After playing around a bit, I thought the way that looks best is to center the text, with a max-width of 1200px so there'll still be a larger gap on extraLarge screens.

2021-07-28 17:11 UTC, mikesoltow commented
@Hplata I'm tagging you to make sure you're okay with the following.  I took a look, and it's fine with me, but I trust your opinion more than mine!
>For the most part I strictly followed the style guide here. The only sort-of exception is the placement of the text. The style guide specifies a dynamic gap between the logo and text, but doesn't indicate how that should be accomplished. After playing around a bit, I thought the way that looks best is to center the text, with a max-width of 1200px so there'll still be a larger gap on extraLarge screens.

Here's what it looks like on a large screen:
![Screen Shot 2021-07-28 at 1 11 21 PM](https://user-images.githubusercontent.com/46460514/127366559-7e270cc4-3d96-458b-9c53-3fe869a8ad85.png)

2021-07-28 21:41 UTC, mikesoltow reviewed
I'm essentially good with this.  I have a suggestion on the tests, but it's not a blocker.  The only other thing that would keep me from approving now is some questions I have about inconsistencies in the Style Guide with regards to link color.  I've pinged Hector and Juan about them, so we'll see what they say.

2021-07-28 21:41 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +export const Footer = styled(FooterBase).attrs({ as: FooterBase, role: 'contentinfo' as string })`
You'll have to remind me what this actually does again.  I'm sure it's legit, but it just reads so strangely as "styled A as A."

2021-07-28 22:01 UTC, wilysword commented on modules/cactus-web/src/Footer/Footer.tsx
> +export const Footer = styled(FooterBase).attrs({ as: FooterBase, role: 'contentinfo' as string })`
When creating an element, `styled-components` does something like this (simplified):
```
const component = attrs.as || props.as || target // where target comes from `styled(target)`
return React.createElement(component, propsPlusAttrs)
```
In this, case, the `as: FooterBase` is the important point, and I could have done `styled.footer` or even `styled(() => null)` and it would have worked the same because the `attrs` overrides everything else. The only reason I did `styled(FooterBase)` is because that tells Typescript what props I'm supposed to have available in the CSS definitions, and it's slightly shorter than
```
styled.footer.attrs(...)<FooterProps>`
  ...etc.
`  as React.FC<FooterProps>
```
It's a pretty small difference, though, so if you (or anyone else) think it would look better or be more readable like that, I don't mind.

2021-07-28 22:05 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +export const Footer = styled(FooterBase).attrs({ as: FooterBase, role: 'contentinfo' as string })`
Got it.  And remind me again why it's important to have `FooterBase` in the `as` prop instead of the target?  Does that have something to do with the "folding" you mentioned in the ToggleCards PR?

2021-07-28 22:09 UTC, mikesoltow requested changes
Unfortunately there was some confusion over the link color in the Style Guide.  We got it sorted out, but there are two small changes to make.

2021-07-28 22:09 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +      color: ${(p) => p.theme.colors.base};
The updated color is now `callToAction`

2021-07-28 22:09 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +      color: ${(p) => p.theme.colors.darkContrast};
The updated color is now `darkestContrast`

2021-07-28 22:13 UTC, wilysword commented on modules/cactus-web/src/Footer/Footer.tsx
> +export const Footer = styled(FooterBase).attrs({ as: FooterBase, role: 'contentinfo' as string })`
It prevents people from breaking the component (or at least getting really weird results) by passing an `as` prop. Honestly it's kind of overkill, since changing the type to `FC<FooterProps>` would make Typescript complain about an `as` prop, and beyond that if someone passes an undocumented prop and breaks their app it's basically their own fault. It makes me feel better, though, to be just that little bit more proof against fools.

2021-07-28 22:55 UTC, wilysword commented on modules/cactus-web/src/Footer/Footer.tsx
> +      color: ${(p) => p.theme.colors.darkContrast};
Just to be sure: the style guide now _says_ darkest contrast, but the color shown is still `darkContrast`. I want to be extra sure here, because it's unusual to have the `:visited` color be the same as regular non-link text. (Although it is for the `dark` variant...)

2021-07-29 16:32 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +export const Footer = styled(FooterBase).attrs({ as: FooterBase, role: 'contentinfo' as string })`
Fair enough!  Thanks for the explanation.

2021-07-29 16:35 UTC, mikesoltow commented on modules/cactus-web/src/Footer/Footer.tsx
> +      color: ${(p) => p.theme.colors.darkContrast};
Okay, I think we've settled on the colors after digging through them even more 🤞 :
* `:visited` for `lightLink` should remain `darkContrast`
* `:focus` for `lightLink` _and_ the `dark` variant should be `{ color: darkContrast, backgroundColor: lightCallToAction }`

2021-07-29 17:01 UTC, wilysword commented on modules/cactus-web/src/Footer/Footer.test.tsx
> +  test('should be able to pass links using a', () => {
I think the styles are well-covered by the storyshots, so I'll remove it.

2021-07-29 17:47 UTC, mikesoltow approved these changes
Thanks, Glen!

2021-08-02 15:26 UTC, daniloPenaR approved these changes

2021-08-02 17:56 UTC, wilysword commented
I already started to fix the conflicts on https://github.com/repaygithub/cactus/pull/635, so I'm just going to wait till that's merged to fix all the conflicts at once.

2021-08-02 21:37 UTC, merged