CACTUS-846 :: Dependency updates
repaygithub/cactus pull request #730
Opened 2022-03-23 20:52 UTC by daniloPenaR

[CACTUS-846](https://repayonline.atlassian.net/browse/CACTUS-846)

2022-03-24 17:18 UTC, wilysword commented
When running `yarn install` I got warnings from `patch-package`. The warning explains how to fix it, though in the case of `react-final-form` you may have to move the patch file afterwards.

2022-03-24 18:00 UTC, wilysword requested changes

2022-03-24 22:25 UTC, daniloPenaR commented
> When running yarn install I got warnings from patch-package. The warning explains how to fix it, though in the case of react-final-form you may have to move the patch file afterwards.


I was going to add that patch commit after solves a problem with the browserstack Internet explorer problem in the `mock-ebpp` tests, it's so annoying, I run yarn test:ci every time I performed an upgrade, and haven't seen this error before the `yarn deduplicate` and `yarn audit` steps.


```bash
Account Integration Tests
GeneralError: The Internet Explorer 11.0 / Windows 10 (https://automate.browserstack.com/builds/940b9b8003a0c2ab6cb5c8913f85fc78d5671a0e/sessions/b0e8ea684d0a64bc385ef9fe7b387ba55473e496) browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.
    at BrowserConnection._createBrowserDisconnectedError (/cactus/node_modules/testcafe/src/browser/connection/index.ts:238:16)
    at Timeout._onTimeout (/cactus/node_modules/testcafe/src/browser/connection/index.ts:243:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'E1002',
  data: [
    'Internet Explorer 11.0 / Windows 10 (https://automate.browserstack.com/builds/940b9b8003a0c2ab6cb5c8913f85fc78d5671a0e/sessions/b0e8ea684d0a64bc385ef9fe7b387ba55473e496)'
  ]
}
```

2022-03-30 17:04 UTC, wilysword commented on patches/react-final-form+6.5.8.patch
> +
You need to move this file to `modules/cactus-form/patches/`, so it will be included in the library release on NPM.

2022-03-30 20:54 UTC, Dhalton reviewed
I think something must've gotten messed up when you were resetting commits, because this looks like it's undoing some of the more recent work and the most recent publishes.

2022-03-30 20:54 UTC, Dhalton commented on modules/cactus-form/CHANGELOG.md
> -# v1.0.2 (Thu Mar 10 2022)
Why remove this from the changelog?

2022-03-30 20:54 UTC, Dhalton commented on modules/cactus-form/package.json
> +  "version": "1.0.1",
Why are you setting this back to 1.0.1? The latest version on npm is 1.0.2: https://www.npmjs.com/package/@repay/cactus-form

2022-03-30 20:54 UTC, Dhalton commented on modules/cactus-icons/package.json
> +  "version": "3.0.2",
Again, why are you setting this back to a previous version? This package is on version 3.1.0. https://www.npmjs.com/package/@repay/cactus-icons

2022-03-31 13:48 UTC, daniloPenaR commented on patches/react-final-form+6.5.8.patch
> +
Must I delete the other patch found in that folder or does it have to be preserved?

2022-03-31 13:51 UTC, daniloPenaR commented on modules/cactus-form/CHANGELOG.md
> -# v1.0.2 (Thu Mar 10 2022)
It's weird, I reverted those changes and now I tried to merge `master` changes into my branch but It says that is _already up to date_, I guess this could be solved by reverting the reverted merge changes to get the recent work lol

2022-04-04 17:16 UTC, wilysword reviewed
You need to fix the `patch-package` warnings. My other comment addresses how I think you should fix the `react-final-form` issue, but you also need to fix the `testcafe` patch.

2022-04-04 17:16 UTC, wilysword commented on modules/cactus-form/package.json
>      "@repay/cactus-web": ">=3.0.0",
Looks like `patch-package` is still complaining; I guess it doesn't work well with multiple versions. Here's what I suggest to fix it:
- Remove `patches/react-final-form+6.5.8.patch` from the root (keep the one in `modules/cactus-form/patches`).
- Remove `modules/cactus-form/patches/react-final-form+6.5.7.patch` (the old version).
- In this file, update the `react-final-form` peer dependency to version `^6.5.8`.

2022-04-05 16:54 UTC, wilysword approved these changes

2022-04-05 17:06 UTC, merged