fix(cactus-web): fix event handling on touch screens
repaygithub/cactus pull request #756
Opened 2022-05-27 21:36 UTC by wilysword

https://repayonline.atlassian.net/browse/CACTUS-454

Apparently touch screens cancel pointer events after a short delay for some reason beyond the ken of mere mortals like me. Fortunately the spec writers weren't complete morons and provided a simple way to restore logical functionality.

### UAT
Chrome-based browser devtools have a touch-screen simulator that I used to reproduce & fix the issue (not sure how to get dev code running on an actual mobile device). Firefox supposedly has something similar, but it didn't reproduce the bug so it can't be used to validate the fix.

2022-05-27 22:50 UTC, Dhalton approved these changes
Was able to test on my phone, works great 👍

2022-05-31 16:32 UTC, maxrcollins commented
This is working perfectly on my android now, but it is still getting stuck on my iPhone.

https://caniuse.com/css-touch-action

`iOS Safari only supports auto and manipulation.`

2022-05-31 16:34 UTC, maxrcollins requested changes
Left in a separate comment that `touch-action: none;` isn't supported on Safari on IOS devices so this didn't fix iPhones

2022-05-31 17:18 UTC, Dhalton commented
> Left in a separate comment that `touch-action: none;` isn't supported on Safari on IOS devices so this didn't fix iPhones

Weird, I tested on my iPhone and I didn't notice any issues. Maybe I just didn't know how to cause the problem? I was just swiping left & right, I thought that would be enough to reproduce it

2022-05-31 17:20 UTC, wilysword commented
@Dhalton caniuse said that the Safari version is tied to the OS version, so I guess his OS version is three years out of date?

2022-05-31 17:57 UTC, maxrcollins commented
@Dhalton @wilysword My iPhone is the work phone that Repay sent me a month ago. 

Also it looks like they may have fixed that tbh. And I'm now realizing that it does work better than it did before that style. Regardless, I just took this screenshot after your fix:
![image](https://user-images.githubusercontent.com/74666099/171252998-48aa3c71-1d32-4e84-afda-095f69d499ce.png)

I'm going to try and figure out what exactly I did.

2022-05-31 18:43 UTC, closed without merging