fix(cactus-web): fix height on MenuBar dark variant
repaygithub/cactus pull request #771
Opened 2022-07-14 16:03 UTC by maxrcollins

Ticket: https://repayonline.atlassian.net/browse/CACTUS-961

Note that this bug isn't outlined in the ticket, but the height is different between the two sized menu bars. I can't tell if it's new or if it's been there a while, but while we're fixing up this component, I'd like to have them be more uniform.

UAT:
Open the Menu bar locally in storybook and check the height between the light and dark variants.

Also make sure everything still looks/works as it should. eg: thin/thick doesn't break anything.

2022-07-14 16:20 UTC, Dhalton approved these changes
LGTM thanks for taking care of this

2022-07-14 16:42 UTC, daniloPenaR approved these changes
LGTM, take in count [this](https://github.com/repaygithub/cactus/pull/772)

2022-07-14 17:07 UTC, wilysword requested changes
This no longer matches the style guide...

2022-07-14 18:12 UTC, maxrcollins commented
> Style guide specifies bottom border on hover should be 3px (4px thick). Technically it also specifies that the focus border should be even all the way around, though I don't mind ignoring that one quite as much. (Regarding the way the text shifted on focus, I actually didn't mind that, since it didn't affect readability but served as a further visual indicator of focus shift.)

I'll see what I can do about the thickness. Right now it's 3px (5px thick) but I think the 1px bigger bottom border is closer to what than the 5px difference in height we had earlier. 

As for the focus state, I see what you mean. I don't really mind the text shifting in the dark theme either but it doesn't currently do that on the light theme. And I DO mind them behaving differently.  If you would rather I leave it as it was before with the text shifting, I can do that but you should bring it up in the thread so we can get a group consensus there and maybe we'd have it do the same in the light theme.

2022-07-14 20:29 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +          inset -1px -1px 0 ${(p) => thicknessMap[p.theme.border]} ${color('white')};
This isn't obvious up front but to keep the menu heights the same size, I couldn't increase/decrease the border size, so I did something a little fancy with a box shadow instead to make the bottom border the correct size

2022-07-14 20:38 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +        padding-bottom: ${(p) => (p.theme.border === 'thin' ? '26px' : '27px')};
I'd suggest using the `borderSize` helper for this kind of statement.

2022-07-14 20:38 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +          inset -1px -1px 0 ${(p) => thicknessMap[p.theme.border]} ${color('white')};
This seems excessively complicated, and is exactly the kind of thing I was afraid of when I decided not to make them the same height. (I still don't understand why that's such a big deal to you...)

If you're really going to do this, I'd suggest using normal borders instead and setting variable padding using the `borderSize` helper.

2022-07-14 21:24 UTC, Dhalton commented
> (I still don't understand why that's such a big deal to you...)

I mean the heights were the same before, and they're the same in the style guide, so isn't increasing the height of the dark variant _also_ a deviation from the style guide?

If it's going to be a huge pain, then let's just release it as-is and see if the channels team pushes back on it.

2022-07-14 22:04 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +          inset -1px -1px 0 ${(p) => thicknessMap[p.theme.border]} ${color('white')};
This change has nothing to do with the height. It has to do with the bottom border being 1px off that you brought up. I was still able to use `insetBorder` until this. I don't care deeply about it being 1px off but it was very noticeable to me that the headers were two different sizes. Also until this change, there was still a small amount of spacing discrepancy between the menu items because of the border on dark mode. Go to the [dev site](https://repaygithub.github.io/cactus/stories/cactus-web/?path=/story/menubar--menu-bar-dark) and switch back and fourth. Fixing the spacing was the point of this ticket to begin with. Changing the color theme should not affect any of the spacing which is why I'm trying to clean this up. The text also shouldn't only be moving only on dark mode only on focus. Each of these individually might not be a big deal but together they absolutely warrant a fix.


Anyway, I'll look into using borderSize or maybe just doing this a different way. I don't really like the box shadow either.

2022-07-14 22:31 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +          inset -1px -1px 0 ${(p) => thicknessMap[p.theme.border]} ${color('white')};
Idea: adjust padding based on `borderSize`, use a regular 1/2px border that changes color to white on hover/focus, along with a 2px inset bottom border on hover only. (Not sure if it'll work because I don't know exactly how the inset border is positioned inside a regular border: do they overlap?)

2022-07-15 00:44 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +          inset -1px -1px 0 ${(p) => thicknessMap[p.theme.border]} ${color('white')};
Heh. I had actually started to do that. Thanks for the suggestion. I'm just trying to figure out a way to make this not look hacked together.

2022-07-15 14:59 UTC, maxrcollins commented
@wilysword I fixed this up in a way that I think you'll be happy with now. It's way cleaner. 

@Dhalton  All of the dimensions of everything stays the same across light/dark theme and nothing moves on hover

2022-07-15 16:52 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +        ${insetBorder('white', 'bottom', { thin: '2px', thick: '2px' })};
One of the things I did to keep the height consistent is to split the border that's always there from the border that gets added on hover. The border that is always there is 1px/2px. The inset border is actually just an inset box shadow which gets added inside the border but doesn't add any height. Since I've set it to 2px/2px, the final height of the white line at the bottom becomes 3px/4px.

Does that make sense?

2022-07-15 17:00 UTC, Dhalton commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +        ${insetBorder('white', 'bottom', { thin: '2px', thick: '2px' })};
Ah, yeah that makes sense. Thanks for explaining

2022-07-15 17:53 UTC, wilysword approved these changes
Functionally looks good, although I think you could still simplify just a bit more. Also make sure you've got the right storyshots generated.

2022-07-15 17:53 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +    }
This doesn't seem to do anything.

2022-07-15 17:53 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +      border: ${border('transparent', { thin: '1px', thick: '2px' })};
These are the default thin/thick values, so you could omit them.

2022-07-15 17:53 UTC, wilysword commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +      padding: calc(24px - ${borderSize()}) calc(16px - ${borderSize()}) 25px;
This is fine, but I think it might be slightly less confusing if you did it like this (matter of opinion?):
```suggestion
      padding: ${borderSize({ thin: '23px 15px 25px', thick: '22px 14px 25px' })};
```

2022-07-15 17:57 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +      padding: calc(24px - ${borderSize()}) calc(16px - ${borderSize()}) 25px;
No you're right. I also want to get rid of calc() because [IE has trouble with math](https://caniuse.com/?search=calc). I think this particular instance is fine, but I still like to avoid it.

2022-07-15 18:00 UTC, maxrcollins commented on modules/cactus-web/src/MenuBar/MenuBar.tsx
> +    }
It adds 1px of padding to the scroll buttons to bring them in line with the size of the dark mode button which gets a border. It's only a 1-2px difference and isn't obvious, even switching between the two themes, but it made everything EXACTLY the same. At the very least, I should've put this outside of the variantMap.

2022-07-15 19:28 UTC, wilysword approved these changes

2022-07-15 20:12 UTC, merged