CACTUS-1055 :: Breaking Changes: Inline Inputs
repaygithub/cactus pull request #844
Opened 2022-12-06 21:28 UTC by daniloPenaR

[CACTUS-1055](https://repayonline.atlassian.net/browse/CACTUS-1055)
This PR is practically focused only on the `TextInput` and `TextArea` components. You can see the commits for more information there. 

### UAT
Ensure the stories and the tests are all passing.

2022-12-07 17:58 UTC, daniloPenaR commented
> I haven't started my review yet, but are https://github.com/repaygithub/cactus/pull/845 visual changes expected? I don't see the difference in most of them, except for the input in the modal. It's noticeably longer now.

I was expecting most of them because of the changes in padding for `TextInput`. But now I realized something else with the modal one, the width is being overwritten to 100%, I'm looking at this now.

2022-12-08 21:46 UTC, wilysword requested changes
Mostly good, couple of minor comments. The bigger problem is that this ticket is meant to apply to _all_ our inputs, not just `TextInput` and `TextArea`.
- `ColorPicker` should change display to `inline-flex`, add `allWidth`.
- `Select` needs to add `display: inline-block` and change `width` to `allWidth`.

All the others appear to be fine as they are. (Well, `DateInput` isn't fine, but it needs way more work than you can put into it in this ticket, so I don't mind if you leave it alone.)

2022-12-08 21:46 UTC, wilysword commented on modules/cactus-web/src/TextArea/TextArea.tsx
>    display: block;
Should be `inline-block`, either change it or just delete this line so it will be left as the browser default.

2022-12-08 21:46 UTC, wilysword commented on modules/cactus-web/src/TextInput/TextInput.tsx
> +import { flexItem, FlexItemProps } from '../helpers/styled'
Change `width`/`WidthProps` to `allWidth` & `AllWidthProps`.

2022-12-08 21:52 UTC, Dhalton reviewed
Other than what Glen mentioned, I only have one comment and another ask: Can you change the argType for the resize prop in the basic usage `TextArea` story to `STRING`? It's defaulting to an object.

2022-12-08 21:52 UTC, Dhalton commented on modules/cactus-web/src/TextArea/TextArea.tsx
> +  resize: PropTypes.oneOf(['none', 'both', 'horizontal', 'vertical', 'initial', 'inherit']),
This proptype doesn't match up with the types that are allowed for this prop. If you pass a responsive array like `resize={['vertical', 'both']}`, you get a proptypes error. It's going to be a pain to get the proptypes to work well with this, though. I wonder if we should even bother with it. It looks like we don't include the proptype for most if not all other responsive props.

2022-12-09 17:39 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  &&& {
Is this higher specificity necessary? I don't think it is...I removed it and was still able to apply width/flex styles.

2022-12-09 17:39 UTC, Dhalton commented on modules/cactus-web/src/ColorPicker/ColorPicker.story.tsx
> +  <Flex flexDirection="column">
I'm putting this here because it's easier, but I think it'd be better to do this in the "controlled" story: could you add the width props to the controls to make it easier to test with?

2022-12-09 17:39 UTC, Dhalton commented on modules/cactus-web/src/Select/Select.story.tsx
> +    <Select {...args} options={showOptions ? options : []} width="100%" />
Can you add the width props to the controls for the story? I'm betting you're using `width="100%"` here to match the storyshots, but we can still add the control and just default it to 100%.

2022-12-09 17:39 UTC, Dhalton commented on modules/cactus-web/src/Select/Select.tsx
> +  &&& {
Is this extra specificity necessary?

2022-12-09 17:55 UTC, wilysword reviewed
I agree with Dhalton's comments regarding the stories/controls, beyond that this looks good.

2022-12-09 17:55 UTC, wilysword commented on modules/cactus-web/src/ColorPicker/ColorPicker.tsx
> +  &&& {
It'll be removed in the inline styles ticket anyway, I wouldn't worry too much about it if I were you.

2022-12-12 20:48 UTC, Dhalton approved these changes

2022-12-13 17:49 UTC, wilysword approved these changes

2022-12-13 20:16 UTC, merged